-- Karibu demo schema END STATE, part 3. GENERATED by build-sql-editor-bundle.sh.
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET row_security = off;
-- Name: chart_access_log; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.chart_access_log ENABLE ROW LEVEL SECURITY;

--
-- Name: clinic_departments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.clinic_departments ENABLE ROW LEVEL SECURITY;

--
-- Name: clinic_departments clinic_departments_read_same_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY clinic_departments_read_same_clinic ON public.clinic_departments FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.staff
  WHERE ((staff.clinic_id = clinic_departments.clinic_id) AND (staff.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (staff.is_active = true) AND (staff.deactivated_at IS NULL)))));


--
-- Name: clinic_lab_capabilities; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.clinic_lab_capabilities ENABLE ROW LEVEL SECURITY;

--
-- Name: clinic_lab_capabilities clinic_lab_capabilities_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY clinic_lab_capabilities_select ON public.clinic_lab_capabilities FOR SELECT USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: clinic_pharmacy_formulary; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.clinic_pharmacy_formulary ENABLE ROW LEVEL SECURITY;

--
-- Name: clinic_pharmacy_formulary clinic_pharmacy_formulary_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY clinic_pharmacy_formulary_select ON public.clinic_pharmacy_formulary FOR SELECT USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: clinic_print_settings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.clinic_print_settings ENABLE ROW LEVEL SECURITY;

--
-- Name: clinic_protocol_enrollments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.clinic_protocol_enrollments ENABLE ROW LEVEL SECURITY;

--
-- Name: clinic_protocol_enrollments clinic_protocol_enrollments_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY clinic_protocol_enrollments_select ON public.clinic_protocol_enrollments FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.staff s
  WHERE ((s.clinic_id = clinic_protocol_enrollments.clinic_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- Name: clinical_protocol_definitions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.clinical_protocol_definitions ENABLE ROW LEVEL SECURITY;

--
-- Name: clinical_protocol_definitions clinical_protocol_definitions_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY clinical_protocol_definitions_select ON public.clinical_protocol_definitions FOR SELECT USING ((active = true));


--
-- Name: clinics; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.clinics ENABLE ROW LEVEL SECURITY;

--
-- Name: cme_flashcards; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cme_flashcards ENABLE ROW LEVEL SECURITY;

--
-- Name: cme_flashcards cme_flashcards_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY cme_flashcards_read ON public.cme_flashcards FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.cme_modules m
  WHERE ((m.id = cme_flashcards.module_id) AND (m.published = true)))));


--
-- Name: cme_lessons; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cme_lessons ENABLE ROW LEVEL SECURITY;

--
-- Name: cme_lessons cme_lessons_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY cme_lessons_read ON public.cme_lessons FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.cme_modules m
  WHERE ((m.id = cme_lessons.module_id) AND (m.published = true)))));


--
-- Name: cme_modules; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cme_modules ENABLE ROW LEVEL SECURITY;

--
-- Name: cme_modules cme_modules_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY cme_modules_read ON public.cme_modules FOR SELECT USING ((published = true));


--
-- Name: cme_quiz_attempts; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cme_quiz_attempts ENABLE ROW LEVEL SECURITY;

--
-- Name: cme_quiz_attempts cme_quiz_attempts_own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY cme_quiz_attempts_own ON public.cme_quiz_attempts USING ((staff_id = ( SELECT staff.id
   FROM public.staff
  WHERE (staff.clerk_user_id = (auth.jwt() ->> 'sub'::text))
 LIMIT 1))) WITH CHECK ((staff_id = ( SELECT staff.id
   FROM public.staff
  WHERE (staff.clerk_user_id = (auth.jwt() ->> 'sub'::text))
 LIMIT 1)));


--
-- Name: cme_quiz_questions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cme_quiz_questions ENABLE ROW LEVEL SECURITY;

--
-- Name: cme_quiz_questions cme_quiz_questions_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY cme_quiz_questions_read ON public.cme_quiz_questions FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.cme_modules m
  WHERE ((m.id = cme_quiz_questions.module_id) AND (m.published = true)))));


--
-- Name: consult_messages; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.consult_messages ENABLE ROW LEVEL SECURITY;

--
-- Name: consult_messages consult_messages_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY consult_messages_clinic ON public.consult_messages USING ((EXISTS ( SELECT 1
   FROM public.consult_threads t
  WHERE ((t.id = consult_messages.thread_id) AND (t.clinic_id = public.get_current_clinic_id()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM public.consult_threads t
  WHERE ((t.id = consult_messages.thread_id) AND (t.clinic_id = public.get_current_clinic_id())))));


--
-- Name: consult_threads; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.consult_threads ENABLE ROW LEVEL SECURITY;

--
-- Name: consult_threads consult_threads_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY consult_threads_clinic ON public.consult_threads USING ((clinic_id = public.get_current_clinic_id())) WITH CHECK ((clinic_id = public.get_current_clinic_id()));


--
-- Name: deliveries; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.deliveries ENABLE ROW LEVEL SECURITY;

--
-- Name: deliveries deliveries_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY deliveries_select_clinic ON public.deliveries FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: diocese_coordinators; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.diocese_coordinators ENABLE ROW LEVEL SECURITY;

--
-- Name: diocese_coordinators diocese_coordinators_select_self; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY diocese_coordinators_select_self ON public.diocese_coordinators FOR SELECT USING ((clerk_user_id = (auth.jwt() ->> 'sub'::text)));


--
-- Name: dispense_records; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.dispense_records ENABLE ROW LEVEL SECURITY;

--
-- Name: dispense_records dispense_records_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY dispense_records_select ON public.dispense_records FOR SELECT USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: ebola_screenings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ebola_screenings ENABLE ROW LEVEL SECURITY;

--
-- Name: ebola_screenings ebola_screenings_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY ebola_screenings_select_clinic ON public.ebola_screenings FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: hiv_care_enrollments hiv_care_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY hiv_care_clinic ON public.hiv_care_enrollments USING ((EXISTS ( SELECT 1
   FROM public.staff s
  WHERE ((s.clinic_id = hiv_care_enrollments.clinic_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- Name: hiv_care_enrollments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.hiv_care_enrollments ENABLE ROW LEVEL SECURITY;

--
-- Name: hmis_106a_elements; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.hmis_106a_elements ENABLE ROW LEVEL SECURITY;

--
-- Name: hmis_106a_elements hmis_106a_elements_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY hmis_106a_elements_read ON public.hmis_106a_elements FOR SELECT USING (true);


--
-- Name: hmis_diagnosis_codes hmis_codes_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY hmis_codes_read ON public.hmis_diagnosis_codes FOR SELECT USING (true);


--
-- Name: hmis_diagnosis_codes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.hmis_diagnosis_codes ENABLE ROW LEVEL SECURITY;

--
-- Name: hts_events; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.hts_events ENABLE ROW LEVEL SECURITY;

--
-- Name: hts_events hts_events_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY hts_events_clinic ON public.hts_events USING ((EXISTS ( SELECT 1
   FROM public.staff s
  WHERE ((s.clinic_id = hts_events.clinic_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- Name: iv_infusion_checks; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.iv_infusion_checks ENABLE ROW LEVEL SECURITY;

--
-- Name: iv_infusion_checks iv_infusion_checks_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY iv_infusion_checks_select_clinic ON public.iv_infusion_checks FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.staff s
  WHERE ((s.clinic_id = iv_infusion_checks.clinic_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- Name: iv_infusions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.iv_infusions ENABLE ROW LEVEL SECURITY;

--
-- Name: iv_infusions iv_infusions_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY iv_infusions_select_clinic ON public.iv_infusions FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.staff s
  WHERE ((s.clinic_id = iv_infusions.clinic_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- Name: lab_stock_items; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.lab_stock_items ENABLE ROW LEVEL SECURITY;

--
-- Name: lab_stock_items lab_stock_items_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY lab_stock_items_select_clinic ON public.lab_stock_items FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: lab_stock_movements; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.lab_stock_movements ENABLE ROW LEVEL SECURITY;

--
-- Name: lab_stock_movements lab_stock_movements_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY lab_stock_movements_select_clinic ON public.lab_stock_movements FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: lab_test_catalog; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.lab_test_catalog ENABLE ROW LEVEL SECURITY;

--
-- Name: lab_test_catalog lab_test_catalog_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY lab_test_catalog_select ON public.lab_test_catalog FOR SELECT TO authenticated USING (true);


--
-- Name: medical_corpus; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.medical_corpus ENABLE ROW LEVEL SECURITY;

--
-- Name: medical_corpus medical_corpus_public_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY medical_corpus_public_select ON public.medical_corpus FOR SELECT USING ((document_id IN ( SELECT medical_documents.id
   FROM public.medical_documents
  WHERE (medical_documents.is_published = true))));


--
-- Name: medical_documents; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.medical_documents ENABLE ROW LEVEL SECURITY;

--
-- Name: medical_documents medical_documents_public_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY medical_documents_public_select ON public.medical_documents FOR SELECT USING ((is_published = true));


--
-- Name: medication_administrations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.medication_administrations ENABLE ROW LEVEL SECURITY;

--
-- Name: medication_administrations medication_administrations_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY medication_administrations_select_clinic ON public.medication_administrations FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: medication_orders; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.medication_orders ENABLE ROW LEVEL SECURITY;

--
-- Name: medication_orders medication_orders_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY medication_orders_select_clinic ON public.medication_orders FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: message_logs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.message_logs ENABLE ROW LEVEL SECURITY;

--
-- Name: patient_notes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.patient_notes ENABLE ROW LEVEL SECURITY;

--
-- Name: patient_notes patient_notes_insert_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY patient_notes_insert_policy ON public.patient_notes FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM public.visits v
  WHERE ((v.id = patient_notes.visit_id) AND (v.clinic_id = public.get_current_clinic_id()) AND (public.is_admin() OR (public.get_current_staff_role() = 'doctor'::text))))));


--
-- Name: patient_notes patient_notes_select_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY patient_notes_select_policy ON public.patient_notes FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.visits v
  WHERE ((v.id = patient_notes.visit_id) AND (v.clinic_id = public.get_current_clinic_id())))));


--
-- Name: patient_notes patient_notes_update_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY patient_notes_update_policy ON public.patient_notes FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM public.visits v
  WHERE ((v.id = patient_notes.visit_id) AND (v.clinic_id = public.get_current_clinic_id()) AND (public.is_admin() OR (public.get_current_staff_role() = 'doctor'::text))))));


--
-- Name: patient_vitals; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.patient_vitals ENABLE ROW LEVEL SECURITY;

--
-- Name: patient_vitals patient_vitals_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY patient_vitals_select ON public.patient_vitals FOR SELECT USING ((patient_id IN ( SELECT patients.id
   FROM public.patients
  WHERE (patients.clinic_id = public.get_current_clinic_id()))));


--
-- Name: patients; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;

--
-- Name: patients patients_insert_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY patients_insert_policy ON public.patients FOR INSERT WITH CHECK ((clinic_id = public.get_current_clinic_id()));


--
-- Name: patients patients_select_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY patients_select_policy ON public.patients FOR SELECT USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: patients patients_update_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY patients_update_policy ON public.patients FOR UPDATE USING (((clinic_id = public.get_current_clinic_id()) AND (public.is_admin() OR (public.get_current_staff_role() = 'doctor'::text))));


--
-- Name: payments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

--
-- Name: payments payments_insert_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY payments_insert_policy ON public.payments FOR INSERT WITH CHECK ((clinic_id = public.get_current_clinic_id()));


--
-- Name: payments payments_select_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY payments_select_policy ON public.payments FOR SELECT USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: payments payments_update_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY payments_update_policy ON public.payments FOR UPDATE USING (((clinic_id = public.get_current_clinic_id()) AND public.is_admin()));


--
-- Name: pharmacy_stock_batches; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pharmacy_stock_batches ENABLE ROW LEVEL SECURITY;

--
-- Name: pharmacy_stock_batches pharmacy_stock_batches_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY pharmacy_stock_batches_select_clinic ON public.pharmacy_stock_batches FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: pharmacy_stock_items; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pharmacy_stock_items ENABLE ROW LEVEL SECURITY;

--
-- Name: pharmacy_stock_items pharmacy_stock_items_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY pharmacy_stock_items_select_clinic ON public.pharmacy_stock_items FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: pharmacy_stock_movements; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pharmacy_stock_movements ENABLE ROW LEVEL SECURITY;

--
-- Name: pharmacy_stock_movements pharmacy_stock_movements_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY pharmacy_stock_movements_select_clinic ON public.pharmacy_stock_movements FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: postnatal_observations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.postnatal_observations ENABLE ROW LEVEL SECURITY;

--
-- Name: postnatal_observations postnatal_observations_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY postnatal_observations_select_clinic ON public.postnatal_observations FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: pregnancies; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pregnancies ENABLE ROW LEVEL SECURITY;

--
-- Name: pregnancies pregnancies_select_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY pregnancies_select_clinic ON public.pregnancies FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: prescription_orders; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.prescription_orders ENABLE ROW LEVEL SECURITY;

--
-- Name: prescription_orders prescription_orders_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY prescription_orders_select ON public.prescription_orders FOR SELECT USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: protocol_activations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.protocol_activations ENABLE ROW LEVEL SECURITY;

--
-- Name: protocol_activations protocol_activations_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY protocol_activations_select ON public.protocol_activations FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.staff s
  WHERE ((s.clinic_id = protocol_activations.clinic_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- Name: provider_note_addendums; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.provider_note_addendums ENABLE ROW LEVEL SECURITY;

--
-- Name: provider_note_addendums provider_note_addendums_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY provider_note_addendums_select ON public.provider_note_addendums FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: provider_note_amendments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.provider_note_amendments ENABLE ROW LEVEL SECURITY;

--
-- Name: provider_note_amendments provider_note_amendments_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY provider_note_amendments_select ON public.provider_note_amendments FOR SELECT TO authenticated USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: provider_notes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.provider_notes ENABLE ROW LEVEL SECURITY;

--
-- Name: provider_notes provider_notes_insert_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY provider_notes_insert_policy ON public.provider_notes FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM public.visits v
  WHERE ((v.id = provider_notes.visit_id) AND (v.clinic_id = public.get_current_clinic_id()) AND (public.is_admin() OR (public.get_current_staff_role() = 'doctor'::text))))));


--
-- Name: provider_notes provider_notes_select_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY provider_notes_select_policy ON public.provider_notes FOR SELECT USING ((EXISTS ( SELECT 1
   FROM (public.patients p
     JOIN public.staff s ON ((s.clinic_id = p.clinic_id)))
  WHERE ((p.id = provider_notes.patient_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- Name: provider_notes provider_notes_update_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY provider_notes_update_policy ON public.provider_notes FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM public.visits v
  WHERE ((v.id = provider_notes.visit_id) AND (v.clinic_id = public.get_current_clinic_id()) AND (public.is_admin() OR (public.get_current_staff_role() = 'doctor'::text))))));


--
-- Name: referrals; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;

--
-- Name: region_protocols; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.region_protocols ENABLE ROW LEVEL SECURITY;

--
-- Name: clinic_print_settings service role full access clinic_print_settings; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "service role full access clinic_print_settings" ON public.clinic_print_settings TO service_role USING (true) WITH CHECK (true);


--
-- Name: staff; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;

--
-- Name: staff_invitations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.staff_invitations ENABLE ROW LEVEL SECURITY;

--
-- Name: staff_invitations staff_invitations_read_same_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY staff_invitations_read_same_clinic ON public.staff_invitations FOR SELECT USING (((clinic_id = public.get_current_clinic_id()) AND (public.is_admin() OR (public.get_current_staff_role() = ANY (ARRAY['doctor'::text, 'clinical_officer'::text, 'midwife'::text])))));


--
-- Name: staff staff_select_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY staff_select_policy ON public.staff FOR SELECT USING (((clinic_id = public.get_current_clinic_id()) OR (clerk_user_id = (auth.jwt() ->> 'sub'::text))));


--
-- Name: staff staff_update_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY staff_update_policy ON public.staff FOR UPDATE USING ((public.is_admin() AND (clinic_id = public.get_current_clinic_id())));


--
-- Name: superadmins; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.superadmins ENABLE ROW LEVEL SECURITY;

--
-- Name: superadmins superadmins_select_self; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY superadmins_select_self ON public.superadmins FOR SELECT USING ((clerk_user_id = (auth.jwt() ->> 'sub'::text)));


--
-- Name: sync_operations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.sync_operations ENABLE ROW LEVEL SECURITY;

--
-- Name: tb_episodes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.tb_episodes ENABLE ROW LEVEL SECURITY;

--
-- Name: tb_episodes tb_episodes_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tb_episodes_clinic ON public.tb_episodes USING ((EXISTS ( SELECT 1
   FROM public.staff s
  WHERE ((s.clinic_id = tb_episodes.clinic_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- Name: tb_preventive_treatment; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.tb_preventive_treatment ENABLE ROW LEVEL SECURITY;

--
-- Name: tb_preventive_treatment tpt_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tpt_clinic ON public.tb_preventive_treatment USING ((EXISTS ( SELECT 1
   FROM public.staff s
  WHERE ((s.clinic_id = tb_preventive_treatment.clinic_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- Name: viral_load_tests; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.viral_load_tests ENABLE ROW LEVEL SECURITY;

--
-- Name: visit_critical_alerts; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.visit_critical_alerts ENABLE ROW LEVEL SECURITY;

--
-- Name: visit_critical_alerts visit_critical_alerts_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY visit_critical_alerts_select ON public.visit_critical_alerts FOR SELECT USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: visit_diagnosis_codes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.visit_diagnosis_codes ENABLE ROW LEVEL SECURITY;

--
-- Name: visit_diagnosis_codes visit_dx_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY visit_dx_delete ON public.visit_diagnosis_codes FOR DELETE USING ((EXISTS ( SELECT 1
   FROM (public.visits v
     JOIN public.staff s ON ((s.clinic_id = v.clinic_id)))
  WHERE ((v.id = visit_diagnosis_codes.visit_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- Name: visit_diagnosis_codes visit_dx_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY visit_dx_insert ON public.visit_diagnosis_codes FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM (public.visits v
     JOIN public.staff s ON ((s.clinic_id = v.clinic_id)))
  WHERE ((v.id = visit_diagnosis_codes.visit_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- Name: visit_diagnosis_codes visit_dx_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY visit_dx_read ON public.visit_diagnosis_codes FOR SELECT USING ((EXISTS ( SELECT 1
   FROM (public.visits v
     JOIN public.staff s ON ((s.clinic_id = v.clinic_id)))
  WHERE ((v.id = visit_diagnosis_codes.visit_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- Name: visits; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.visits ENABLE ROW LEVEL SECURITY;

--
-- Name: visits visits_insert_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY visits_insert_policy ON public.visits FOR INSERT WITH CHECK ((clinic_id = public.get_current_clinic_id()));


--
-- Name: visits visits_select_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY visits_select_policy ON public.visits FOR SELECT USING ((clinic_id = public.get_current_clinic_id()));


--
-- Name: visits visits_update_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY visits_update_policy ON public.visits FOR UPDATE USING (((clinic_id = public.get_current_clinic_id()) AND (public.is_admin() OR (doctor_id = public.get_current_staff_id()))));


--
-- Name: viral_load_tests vl_tests_clinic; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY vl_tests_clinic ON public.viral_load_tests USING ((EXISTS ( SELECT 1
   FROM public.staff s
  WHERE ((s.clinic_id = viral_load_tests.clinic_id) AND (s.clerk_user_id = (auth.jwt() ->> 'sub'::text)) AND (s.is_active = true)))));


--
-- PostgreSQL database dump complete
--


