-- GENERATED by scripts/build-reference-seed.sh — do not edit by hand.
-- Global reference data extracted from packages/supabase/migrations.
-- All statements are idempotent (ON CONFLICT / UPDATE).

-- from 064_structured_pharmacy.sql:27
INSERT INTO medication_catalog (code, generic_name, strength, formulation, unit, category)
VALUES
  ('AL', 'Artemether/Lumefantrine (AL)', '20/120 mg', 'tablet', 'tab', 'Antimalarials'),
  ('ARTESUNATE', 'Artesunate (IV/IM)', '60mg', 'injection', 'vial', 'Antimalarials'),
  ('DHA_PPQ', 'Dihydroartemisinin/Piperaquine', '40/320 mg', 'tablet', 'tab', 'Antimalarials'),
  ('AMOX', 'Amoxicillin', NULL, 'capsule', 'cap', 'Antibiotics'),
  ('AMOX_CLAV', 'Amoxicillin / Clavulanic acid', NULL, 'tablet', 'tab', 'Antibiotics'),
  ('COTRIM', 'Cotrimoxazole', NULL, 'tablet', 'tab', 'Antibiotics'),
  ('CIPRO', 'Ciprofloxacin', NULL, 'tablet', 'tab', 'Antibiotics'),
  ('ERYTHRO', 'Erythromycin', NULL, 'tablet', 'tab', 'Antibiotics'),
  ('METRO', 'Metronidazole', NULL, 'tablet', 'tab', 'Antibiotics'),
  ('PARA', 'Paracetamol', NULL, 'tablet', 'tab', 'Analgesics'),
  ('IBU', 'Ibuprofen', NULL, 'tablet', 'tab', 'Analgesics'),
  ('ORS', 'ORS (oral rehydration salts)', NULL, 'sachet', 'sachet', 'Fluids'),
  ('ZINC', 'Zinc sulfate', NULL, 'tablet', 'tab', 'Supplements'),
  ('IRON_FOLATE', 'Iron + folic acid', NULL, 'tablet', 'tab', 'Supplements'),
  ('MEBEND', 'Mebendazole', NULL, 'tablet', 'tab', 'Anthelmintics'),
  ('ALBEND', 'Albendazole', NULL, 'tablet', 'tab', 'Anthelmintics'),
  ('PROMETH', 'Promethazine', NULL, 'tablet', 'tab', 'Antihistamines'),
  ('HCTZ', 'Hydrochlorothiazide', NULL, 'tablet', 'tab', 'Cardiovascular'),
  ('NIFED', 'Nifedipine', NULL, 'tablet', 'tab', 'Cardiovascular'),
  ('METHYL', 'Methyldopa', NULL, 'tablet', 'tab', 'Cardiovascular'),
  ('SALB', 'Salbutamol', NULL, 'inhaler', 'dose', 'Respiratory'),
  ('OXY', 'Oxytocin (IV/IM)', '10IU/mL', 'injection', 'vial', 'Obstetrics'),
  ('MGSO4', 'Magnesium sulfate', '50%', 'injection', 'vial', 'Obstetrics'),
  ('TT', 'Tetanus toxoid (TT)', '0.5mL', 'injection', 'dose', 'Vaccines'),
  ('VIT_A', 'Vitamin A', NULL, 'capsule', 'cap', 'Supplements')
ON CONFLICT (code) DO NOTHING;

-- from 080_medication_catalog_formulary.sql:36
INSERT INTO medication_catalog (
  code, generic_name, strength, formulation, unit, category,
  aliases, strengths, default_frequency, default_route, warning_text, display_order, active
) VALUES
  ('AL', 'Artemether/Lumefantrine (AL)', '20/120 mg', 'tablet', 'tab', 'Antimalarials',
    ARRAY['Coartem'], ARRAY['20/120 mg'], 'BID', 'PO', NULL, 10, TRUE),
  ('ARTESUNATE', 'Artesunate (IV/IM)', '60mg', 'injection', 'vial', 'Antimalarials',
    ARRAY[]::TEXT[], ARRAY['60mg vial'], 'STAT', 'IV', 'Severe malaria only. Refer if HC III cannot administer.', 11, TRUE),
  ('DHA_PPQ', 'Dihydroartemisinin/Piperaquine', '40/320 mg', 'tablet', 'tab', 'Antimalarials',
    ARRAY[]::TEXT[], ARRAY['40/320 mg'], 'OD', 'PO', NULL, 12, TRUE),
  ('AMOX', 'Amoxicillin', NULL, 'capsule', 'cap', 'Antibiotics',
    ARRAY[]::TEXT[], ARRAY['250mg cap', '500mg cap', '125mg/5mL susp', '250mg/5mL susp'], 'TID', 'PO', NULL, 20, TRUE),
  ('AMOX_CLAV', 'Amoxicillin / Clavulanic acid', NULL, 'tablet', 'tab', 'Antibiotics',
    ARRAY[]::TEXT[], ARRAY['625mg tab', '1g tab', '228mg/5mL susp'], 'BID', 'PO', NULL, 21, TRUE),
  ('COTRIM', 'Cotrimoxazole', NULL, 'tablet', 'tab', 'Antibiotics',
    ARRAY[]::TEXT[], ARRAY['480mg tab', '960mg tab', '240mg/5mL susp'], 'BID', 'PO', NULL, 22, TRUE),
  ('CIPRO', 'Ciprofloxacin', NULL, 'tablet', 'tab', 'Antibiotics',
    ARRAY[]::TEXT[], ARRAY['250mg tab', '500mg tab'], 'BID', 'PO', NULL, 23, TRUE),
  ('METRO', 'Metronidazole', NULL, 'tablet', 'tab', 'Antibiotics',
    ARRAY[]::TEXT[], ARRAY['200mg tab', '400mg tab', '200mg/5mL susp'], 'TID', 'PO', NULL, 24, TRUE),
  ('ERY', 'Erythromycin', NULL, 'tablet', 'tab', 'Antibiotics',
    ARRAY[]::TEXT[], ARRAY['250mg tab', '125mg/5mL susp'], 'QID', 'PO', NULL, 25, TRUE),
  ('DOXY', 'Doxycycline', NULL, 'capsule', 'cap', 'Antibiotics',
    ARRAY[]::TEXT[], ARRAY['100mg cap'], 'BID', 'PO', 'Contraindicated <8y and in pregnancy.', 26, TRUE),
  ('MEBEN', 'Mebendazole', NULL, 'tablet', 'tab', 'Antihelminthics',
    ARRAY[]::TEXT[], ARRAY['100mg tab', '500mg tab'], 'STAT', 'PO', NULL, 30, TRUE),
  ('ALBEN', 'Albendazole', NULL, 'tablet', 'tab', 'Antihelminthics',
    ARRAY[]::TEXT[], ARRAY['400mg tab'], 'STAT', 'PO', NULL, 31, TRUE),
  ('PARA', 'Paracetamol', NULL, 'tablet', 'tab', 'Analgesics',
    ARRAY[]::TEXT[], ARRAY['500mg tab', '120mg/5mL susp', '250mg/5mL susp'], 'QID', 'PO', NULL, 40, TRUE),
  ('IBU', 'Ibuprofen', NULL, 'tablet', 'tab', 'Analgesics',
    ARRAY[]::TEXT[], ARRAY['200mg tab', '400mg tab', '100mg/5mL susp'], 'TID', 'PO', NULL, 41, TRUE),
  ('DICLO', 'Diclofenac', NULL, 'tablet', 'tab', 'Analgesics',
    ARRAY[]::TEXT[], ARRAY['50mg tab', '75mg IM'], 'BID', 'PO', NULL, 42, TRUE),
  ('ORS', 'ORS (oral rehydration salts)', NULL, 'sachet', 'sachet', 'Rehydration',
    ARRAY[]::TEXT[], ARRAY['1L sachet'], 'PRN', 'PO', NULL, 50, TRUE),
  ('ZINC', 'Zinc sulfate', NULL, 'tablet', 'tab', 'Supplements',
    ARRAY[]::TEXT[], ARRAY['20mg tab'], 'OD', 'PO', NULL, 51, TRUE),
  ('IRON_FOLATE', 'Iron + folic acid', NULL, 'tablet', 'tab', 'Supplements',
    ARRAY[]::TEXT[], ARRAY['60mg/0.4mg', 'tablet'], 'OD', 'PO', NULL, 52, TRUE),
  ('VITA', 'Vitamin A', NULL, 'capsule', 'cap', 'Supplements',
    ARRAY[]::TEXT[], ARRAY['100,000 IU', '200,000 IU'], 'STAT', 'PO', NULL, 53, TRUE),
  ('HCTZ', 'Hydrochlorothiazide', NULL, 'tablet', 'tab', 'Cardiovascular',
    ARRAY[]::TEXT[], ARRAY['25mg tab'], 'OD', 'PO', NULL, 60, TRUE),
  ('NIFED', 'Nifedipine (LA)', NULL, 'tablet', 'tab', 'Cardiovascular',
    ARRAY[]::TEXT[], ARRAY['20mg LA', '30mg LA'], 'BID', 'PO', NULL, 61, TRUE),
  ('METHYL', 'Methyldopa', NULL, 'tablet', 'tab', 'Cardiovascular',
    ARRAY[]::TEXT[], ARRAY['250mg tab', '500mg tab'], 'BID', 'PO', 'First-line for hypertension in pregnancy.', 62, TRUE),
  ('SALB', 'Salbutamol', NULL, 'inhaler', 'dose', 'Respiratory',
    ARRAY[]::TEXT[], ARRAY['4mg tab', '2mg/5mL syrup', '100mcg MDI', 'Neb'], 'PRN', 'Inhaled', NULL, 70, TRUE),
  ('PRED', 'Prednisolone', NULL, 'tablet', 'tab', 'Respiratory',
    ARRAY[]::TEXT[], ARRAY['5mg tab'], 'OD', 'PO', NULL, 71, TRUE),
  ('PROMETH', 'Promethazine', NULL, 'tablet', 'tab', 'Antihistamines',
    ARRAY[]::TEXT[], ARRAY['25mg tab', '5mg/5mL syrup'], 'HS', 'PO', NULL, 80, TRUE),
  ('CETIRI', 'Cetirizine', NULL, 'tablet', 'tab', 'Antihistamines',
    ARRAY[]::TEXT[], ARRAY['10mg tab', '5mg/5mL syrup'], 'OD', 'PO', NULL, 81, TRUE),
  ('OXY', 'Oxytocin (IV/IM)', '10IU/mL', 'injection', 'vial', 'Obstetrics',
    ARRAY[]::TEXT[], ARRAY['10IU/mL'], 'STAT', 'IM', 'PPH protocol — refer for ongoing infusion.', 90, TRUE),
  ('MGSO4', 'Magnesium sulfate', '50%', 'injection', 'vial', 'Obstetrics',
    ARRAY[]::TEXT[], ARRAY['50% inj'], 'STAT', 'IM', 'Eclampsia / pre-eclampsia — Pritchard regimen.', 91, TRUE),
  ('TT', 'Tetanus toxoid (TT)', '0.5mL', 'injection', 'dose', 'Vaccines',
    ARRAY[]::TEXT[], ARRAY['0.5mL'], 'STAT', 'IM', NULL, 100, TRUE)
ON CONFLICT (code) DO UPDATE SET
  generic_name = EXCLUDED.generic_name,
  strength = COALESCE(EXCLUDED.strength, medication_catalog.strength),
  formulation = EXCLUDED.formulation,
  unit = EXCLUDED.unit,
  category = EXCLUDED.category,
  aliases = EXCLUDED.aliases,
  strengths = EXCLUDED.strengths,
  default_frequency = EXCLUDED.default_frequency,
  default_route = EXCLUDED.default_route,
  warning_text = EXCLUDED.warning_text,
  display_order = EXCLUDED.display_order,
  active = EXCLUDED.active;

-- from 069_lab_test_catalog.sql:21
INSERT INTO lab_test_catalog (code, test_name, category, specimen, display_order) VALUES
  ('MRDT',       'Malaria RDT',                       'malaria',       'blood',  10),
  ('BS_MPS',     'Blood slide for malaria parasites', 'malaria',       'blood',  11),
  ('HIV_RDT',    'HIV rapid test',                    'serology',      'blood',  20),
  ('HB',         'Haemoglobin',                       'hematology',    'blood',  30),
  ('AFB',        'Sputum smear (AFB / TB)',           'microbiology',  'sputum', 40),
  ('URINALYSIS', 'Urinalysis',                        'urine',         'urine',  50),
  ('STOOL_OC',   'Stool microscopy (ova/cysts)',      'microbiology',  'stool',  60),
  ('RBS',        'Random blood sugar',                'biochemistry',  'blood',  70),
  ('SYPHILIS',   'Syphilis test (RPR/TPHA)',          'serology',      'blood',  80),
  ('UCG',        'Pregnancy test (UCG)',              'serology',      'urine',  90),
  ('WIDAL',      'Widal test (typhoid)',              'serology',      'blood', 100),
  ('STOOL_RDT',  'Stool antigen / H. pylori RDT',     'microbiology',  'stool', 110)
ON CONFLICT (code) DO NOTHING;

-- from 088_hiv_tb_program_registry.sql:911
INSERT INTO lab_test_catalog (code, test_name, category, specimen, display_order) VALUES
  ('GENEXPERT', 'GeneXpert MTB/RIF',           'microbiology', 'sputum', 41),
  ('CD4',       'CD4 count',                   'serology',     'blood',  21),
  ('VIRAL_LOAD','HIV viral load',                'serology',     'blood',  22),
  ('CRAG',      'Cryptococcal antigen (CrAg)', 'serology',     'blood',  23)
ON CONFLICT (code) DO NOTHING;

-- from 112_lab_catalog_hep_b_brucellosis.sql
INSERT INTO lab_test_catalog (code, test_name, category, specimen, display_order, default_price_ugx) VALUES
  ('HBSAG',   'Hepatitis B rapid test (HBsAg)', 'serology', 'blood', 24, 2500),
  ('BRU_RDT', 'Brucellosis rapid test',         'serology', 'blood', 25, 2500)
ON CONFLICT (code) DO NOTHING;

-- from 076_billing_itemized.sql:10
UPDATE lab_test_catalog SET default_price_ugx = CASE code
  WHEN 'MRDT'       THEN 1500
  WHEN 'BS_MPS'     THEN 3000
  WHEN 'HIV_RDT'    THEN 2000
  WHEN 'HBSAG'      THEN 2500
  WHEN 'BRU_RDT'    THEN 2500
  WHEN 'HB'         THEN 3500
  WHEN 'AFB'        THEN 4000
  WHEN 'URINALYSIS' THEN 2500
  WHEN 'STOOL_OC'   THEN 3000
  WHEN 'RBS'        THEN 2500
  WHEN 'SYPHILIS'   THEN 3000
  WHEN 'UCG'        THEN 2000
  WHEN 'WIDAL'      THEN 3500
  WHEN 'STOOL_RDT'  THEN 2500
  ELSE default_price_ugx
END;

-- from 076_billing_itemized.sql:38
UPDATE medication_catalog SET default_price_ugx = CASE code
  WHEN 'AL'          THEN 500
  WHEN 'ARTESUNATE'  THEN 8000
  WHEN 'DHA_PPQ'     THEN 600
  WHEN 'AMOX'        THEN 200
  WHEN 'AMOX_CLAV'   THEN 400
  WHEN 'COTRIM'      THEN 150
  WHEN 'CIPRO'       THEN 300
  WHEN 'ERYTHRO'     THEN 250
  WHEN 'METRO'       THEN 200
  WHEN 'PARA'        THEN 100
  WHEN 'IBU'         THEN 150
  WHEN 'ORS'         THEN 500
  WHEN 'ZINC'        THEN 100
  WHEN 'IRON_FOLATE' THEN 100
  WHEN 'MEBEND'      THEN 200
  WHEN 'ALBEND'      THEN 200
  WHEN 'PROMETH'     THEN 150
  WHEN 'HCTZ'        THEN 100
  WHEN 'NIFED'       THEN 200
  WHEN 'METHYL'      THEN 150
  WHEN 'SALB'        THEN 500
  WHEN 'OXY'         THEN 5000
  WHEN 'MGSO4'       THEN 3000
  WHEN 'TT'          THEN 2000
  WHEN 'VIT_A'       THEN 300
  ELSE COALESCE(default_price_ugx, 200)
END
WHERE default_price_ugx IS NULL OR default_price_ugx = 0;

-- from 013_hmis_reporting.sql:37
INSERT INTO hmis_diagnosis_codes (hmis_code, category, subcategory, display_name, icd10_codes, sort_order) VALUES
  ('HMIS_105_1.1',  'Malaria',           'Confirmed (microscopy/RDT)', 'Malaria - Confirmed',              ARRAY['B50','B51','B52','B53','B54'], 1),
  ('HMIS_105_1.2',  'Malaria',           'Clinical (suspected)',       'Malaria - Clinical (suspected)',    ARRAY['B54'],                         2),
  ('HMIS_105_2.1',  'Pneumonia',         NULL,                         'Pneumonia',                         ARRAY['J12','J13','J14','J15','J16','J17','J18'], 3),
  ('HMIS_105_3.1',  'Diarrhoea',         'Acute watery',               'Diarrhoea - Acute watery',         ARRAY['A09','K52.9'],                 4),
  ('HMIS_105_3.2',  'Diarrhoea',         'Bloody (dysentery)',         'Diarrhoea - Bloody (dysentery)',    ARRAY['A06.0','A03','A04'],           5),
  ('HMIS_105_3.3',  'Diarrhoea',         'Persistent',                 'Diarrhoea - Persistent',           ARRAY['A09','K52.9'],                 6),
  ('HMIS_105_4',    'Urinary Tract Infection', NULL,                   'Urinary Tract Infection',           ARRAY['N39.0','N30'],                 7),
  ('HMIS_105_5',    'Intestinal Worms',  NULL,                         'Intestinal Worms',                  ARRAY['B76','B77','B79','B68','B82'], 8),
  ('HMIS_105_6',    'Skin Diseases',     NULL,                         'Skin Diseases',                     ARRAY['L00','L08','L20','L30','B35','B36','B37'], 9),
  ('HMIS_105_7',    'Eye Conditions',    NULL,                         'Eye Conditions',                    ARRAY['H10','H00','H04','H16'],       10),
  ('HMIS_105_8',    'Ear Conditions',    NULL,                         'Ear Conditions',                    ARRAY['H60','H65','H66','H70'],       11),
  ('HMIS_105_9',    'Dental Conditions', NULL,                         'Dental Conditions',                 ARRAY['K00','K01','K02','K04','K05'], 12),
  ('HMIS_105_10',   'Injuries',          'Road traffic',               'Injuries - Road traffic',           ARRAY['V01-V99'],                     13),
  ('HMIS_105_11',   'Injuries',          'Other trauma',               'Injuries - Other trauma',           ARRAY['W00-X59','S00-T98'],           14),
  ('HMIS_105_12',   'Anaemia',           NULL,                         'Anaemia',                           ARRAY['D50','D51','D52','D53','D64'], 15),
  ('HMIS_105_13',   'Hypertension',      NULL,                         'Hypertension',                      ARRAY['I10','I11','I12','I13','I15'], 16),
  ('HMIS_105_14',   'Diabetes Mellitus', NULL,                         'Diabetes Mellitus',                 ARRAY['E10','E11','E13','E14'],       17),
  ('HMIS_105_15',   'Mental Health Disorders', NULL,                   'Mental Health Disorders',            ARRAY['F00','F20','F30','F32','F40','F41','F99'], 18),
  ('HMIS_105_16',   'Epilepsy',          NULL,                         'Epilepsy',                          ARRAY['G40','G41'],                   19),
  ('HMIS_105_17',   'HIV/AIDS',          'New positive',               'HIV/AIDS - New positive',           ARRAY['B20','B21','B22','B23','B24'], 20),
  ('HMIS_105_18',   'Tuberculosis',      'New',                        'Tuberculosis - New',                ARRAY['A15','A16','A19'],             21),
  ('HMIS_105_19',   'Tuberculosis',      'Relapse',                    'Tuberculosis - Relapse',            ARRAY['A15','A16','A19'],             22),
  ('HMIS_105_20',   'Sexually Transmitted Infections', NULL,           'Sexually Transmitted Infections',   ARRAY['A50','A51','A52','A54','A55','A56','A63','A64'], 23),
  ('HMIS_105_21',   'Hepatitis B',       NULL,                         'Hepatitis B',                       ARRAY['B16','B18.1'],                 24),
  ('HMIS_105_22',   'Typhoid Fever',     NULL,                         'Typhoid Fever',                     ARRAY['A01.0'],                       25),
  ('HMIS_105_23',   'Measles',           NULL,                         'Measles',                           ARRAY['B05'],                         26),
  ('HMIS_105_24',   'Meningitis',        NULL,                         'Meningitis',                        ARRAY['G00','G01','G02','G03'],       27),
  ('HMIS_105_25',   'Cough / Cold (URTI)', NULL,                      'Cough / Cold (URTI)',               ARRAY['J00','J01','J02','J03','J04','J06'], 28),
  ('HMIS_105_26',   'Abdominal Conditions', NULL,                     'Abdominal Conditions',              ARRAY['K35','K40','K59','R10'],       29),
  ('HMIS_105_27',   'Musculoskeletal Conditions', NULL,               'Musculoskeletal Conditions',         ARRAY['M54','M79','M25'],             30),
  ('HMIS_105_28',   'Malnutrition',      NULL,                         'Malnutrition',                      ARRAY['E40','E41','E42','E43','E44','E46'], 31),
  ('HMIS_105_29',   'Obstetric Conditions', NULL,                     'Obstetric Conditions',               ARRAY['O00','O10','O20','O60','O80'], 32),
  ('HMIS_105_30',   'Neonatal Conditions', NULL,                      'Neonatal Conditions',                ARRAY['P07','P22','P36','P59'],       33),
  ('HMIS_105_31',   'Cardiovascular Disease', NULL,                   'Cardiovascular Disease (other)',     ARRAY['I20','I25','I50','I63','I64'], 34),
  ('HMIS_105_32',   'Asthma',            NULL,                         'Asthma',                            ARRAY['J45','J46'],                   35),
  ('HMIS_105_33',   'Sickle Cell Disease', NULL,                      'Sickle Cell Disease',                ARRAY['D57'],                         36),
  ('HMIS_105_34',   'Cancer',            NULL,                         'Cancer (all types)',                 ARRAY['C00-C97'],                     37),
  ('HMIS_105_35',   'Poisoning',         NULL,                         'Poisoning',                         ARRAY['T36-T65'],                     38),
  ('HMIS_105_36',   'Animal Bites',      NULL,                         'Animal Bites (rabies exposure)',     ARRAY['W54','T14.1'],                 39),
  ('HMIS_105_99',   'Other Diagnoses',   NULL,                         'All Other Diagnoses',               ARRAY[]::TEXT[],                       40),
  ('HMIS_105_OPD_DEATHS', 'OPD Deaths',  NULL,                        'Deaths in OPD',                     ARRAY[]::TEXT[],                       41)
ON CONFLICT (hmis_code) DO NOTHING;

-- from 088_hiv_tb_program_registry.sql:80
INSERT INTO hmis_106a_elements (element_code, report, section, display_name, dhis2_hint, sort_order) VALUES
  -- HCT (HMIS 106a HIV — TABLE 5 HCT)
  ('HIV_HCT_COUNSELED', 'hiv', 'hct', 'Individuals counseled for HIV/AIDS', 'HMIS 106a:01 HCT', 1),
  ('HIV_HCT_TESTED', 'hiv', 'hct', 'Individuals tested for HIV', NULL, 2),
  ('HIV_HCT_RESULT_RECEIVED', 'hiv', 'hct', 'Individuals who received HIV test results', NULL, 3),
  ('HIV_HCT_FIRST_RESULT_FY', 'hiv', 'hct', 'First HIV result in financial year', NULL, 4),
  ('HIV_HCT_POSITIVE', 'hiv', 'hct', 'Individuals who tested HIV positive', NULL, 5),
  ('HIV_HCT_SUSPECT_TB', 'hiv', 'hct', 'HIV positive with suspected TB', NULL, 6),
  ('HIV_HCT_STARTED_CPT', 'hiv', 'hct', 'HIV positive started on CPT', NULL, 7),
  ('HIV_HCT_RETESTER', 'hiv', 'hct', 'Re-testers (2+ tests in last 12 months)', NULL, 8),
  ('HIV_HCT_COUPLE_TESTED', 'hiv', 'hct', 'Couple tested together', NULL, 9),
  ('HIV_HCT_COUPLE_CONCORDANT', 'hiv', 'hct', 'Couple concordant positive', NULL, 10),
  ('HIV_HCT_COUPLE_DISCORDANT', 'hiv', 'hct', 'Couple discordant', NULL, 11),
  ('HIV_HCT_PEP', 'hiv', 'hct', 'Individuals counseled and tested for PEP', NULL, 12),
  ('HIV_HCT_SMC', 'hiv', 'hct', 'Safe male circumcision provided', NULL, 13),
  -- ART (HMIS 106a HIV — ART services)
  ('HIV_ART_NEW_ENROLLED', 'hiv', 'art', 'New patients enrolled in HIV care (quarter)', NULL, 20),
  ('HIV_ART_NEW_ON_ART', 'hiv', 'art', 'New patients started on ART (quarter)', NULL, 21),
  ('HIV_ART_PREGNANT_ENROLLED', 'hiv', 'art', 'Pregnant women enrolled in care (quarter)', NULL, 22),
  ('HIV_ART_PREGNANT_ON_ART', 'hiv', 'art', 'Pregnant women started on ART (quarter)', NULL, 23),
  ('HIV_ART_ACTIVE_PREART', 'hiv', 'art', 'Active on pre-ART care (end of quarter)', NULL, 24),
  ('HIV_ART_CPT_LAST_VISIT', 'hiv', 'art', 'Received CPT at last visit (quarter)', NULL, 25),
  ('HIV_ART_ELIGIBLE_NOT_ART', 'hiv', 'art', 'Eligible not yet on ART (end of quarter)', NULL, 26),
  ('HIV_ART_ACTIVE_ON_ART', 'hiv', 'art', 'Active on ART (end of quarter)', NULL, 27),
  ('HIV_ART_TB_SCREENED', 'hiv', 'art', 'PLHIV screened for TB at last visit', NULL, 28),
  ('HIV_ART_TB_TREATMENT', 'hiv', 'art', 'PLHIV started on TB treatment (quarter)', NULL, 29),
  ('HIV_VL_TESTED', 'hiv', 'art', 'Viral load tests done (quarter)', NULL, 30),
  ('HIV_VL_SUPPRESSED', 'hiv', 'art', 'Viral load suppressed (<1000 copies/mL)', NULL, 31),
  ('HIV_VL_NOT_SUPPRESSED', 'hiv', 'art', 'Viral load not suppressed', NULL, 32),
  -- TB case-finding (HMIS 106a:03)
  ('TB_NEW_SMEAR_POS', 'tb', 'casefinding', 'New pulmonary smear-positive', 'NTLP quarterly case-finding', 1),
  ('TB_NEW_SMEAR_NEG', 'tb', 'casefinding', 'New pulmonary smear-negative', NULL, 2),
  ('TB_NEW_EPT', 'tb', 'casefinding', 'New extrapulmonary', NULL, 3),
  ('TB_RELAPSE', 'tb', 'casefinding', 'Relapse', NULL, 4),
  ('TB_RETREAT_DEFAULT', 'tb', 'casefinding', 'Retreatment after default', NULL, 5),
  ('TB_FAILURE', 'tb', 'casefinding', 'Treatment failure', NULL, 6),
  ('TB_OTHER', 'tb', 'casefinding', 'Other registered cases', NULL, 7),
  ('TB_HIV_POSITIVE', 'tb', 'casefinding', 'TB cases HIV positive', NULL, 8),
  ('TB_TREATMENT_STARTED', 'tb', 'casefinding', 'Started on TB treatment (quarter)', NULL, 9),
  -- TB outcomes (cohort completing in quarter)
  ('TB_OUTCOME_CURED', 'tb', 'outcomes', 'Treatment outcome: Cured', NULL, 20),
  ('TB_OUTCOME_COMPLETED', 'tb', 'outcomes', 'Treatment outcome: Completed', NULL, 21),
  ('TB_OUTCOME_FAILURE', 'tb', 'outcomes', 'Treatment outcome: Failure', NULL, 22),
  ('TB_OUTCOME_DEFAULT', 'tb', 'outcomes', 'Treatment outcome: Default', NULL, 23),
  ('TB_OUTCOME_TRANSFERRED', 'tb', 'outcomes', 'Treatment outcome: Transferred out', NULL, 24),
  ('TB_OUTCOME_DIED', 'tb', 'outcomes', 'Treatment outcome: Died', NULL, 25),
  -- TPT
  ('TPT_PLHIV_STARTED', 'tb', 'tpt', 'TPT started — PLHIV', NULL, 30),
  ('TPT_PLHIV_COMPLETED', 'tb', 'tpt', 'TPT completed — PLHIV', NULL, 31),
  ('TPT_CHILD_STARTED', 'tb', 'tpt', 'TPT started — child <5 household contact', NULL, 32),
  ('TPT_CHILD_COMPLETED', 'tb', 'tpt', 'TPT completed — child <5 household contact', NULL, 33)
ON CONFLICT (element_code) DO NOTHING;

-- from 048_ehr_pilot_architecture.sql:379
INSERT INTO clinical_protocol_definitions (slug, title, description, trigger_hint, steps, lab_bundle, isolation_required)
VALUES
  (
    'ebola-suspect-v1',
    'Ebola suspect protocol',
    'Suspected Ebola virus disease — isolation, PPE, notify supervisor, send specimens per MOH guidance.',
    'Fever + bleeding, contact with confirmed case, or unexplained hemorrhagic illness',
    '[
      {"type":"care_task","title":"Initiate isolation","assignee_role":"nurse"},
      {"type":"care_task","title":"Notify facility supervisor","assignee_role":"admin"},
      {"type":"care_task","title":"Don PPE before contact","assignee_role":"nurse"}
    ]'::jsonb,
    '["Ebola PCR","Malaria RDT","Full blood count"]'::jsonb,
    TRUE
  ),
  (
    'cholera-suspect-v1',
    'Cholera suspect protocol',
    'Acute watery diarrhea cluster — rehydration, stool specimen, infection control.',
    'Profuse watery diarrhea, dehydration, outbreak context',
    '[
      {"type":"care_task","title":"Start oral/IV rehydration","assignee_role":"nurse"},
      {"type":"care_task","title":"Collect stool specimen","assignee_role":"lab_tech"}
    ]'::jsonb,
    '["Stool culture","RDT cholera if available"]'::jsonb,
    FALSE
  )
ON CONFLICT (slug) DO NOTHING;

