-- GENERATED by scripts/build-reference-seed.sh — do not edit by hand.
-- Per-clinic backfills extracted from packages/supabase/migrations.
-- Run AFTER seed/20_demo_census.sql (needs clinic rows to exist).
-- All statements are idempotent and scoped by SELECT ... FROM clinics.

-- from 033_clinician_authority_ai_review.sql:139
INSERT INTO clinic_lab_capabilities (clinic_id, test_name, is_available)
SELECT c.id, lab.test_name, TRUE
FROM clinics c
CROSS JOIN (VALUES
  ('Malaria RDT'),
  ('Blood slide microscopy (malaria)'),
  ('HIV rapid test'),
  ('Hepatitis B test'),
  ('Syphilis (RPR) test'),
  ('Urinalysis (urine dipstick)'),
  ('Urine pregnancy test'),
  ('Hemoglobin estimation'),
  ('Stool microscopy'),
  ('Blood glucose')
) AS lab(test_name)
ON CONFLICT (clinic_id, test_name) DO NOTHING;

-- from 033_clinician_authority_ai_review.sql:160
INSERT INTO clinic_pharmacy_formulary (clinic_id, drug_name, in_stock)
SELECT c.id, drug.name, TRUE
FROM clinics c
CROSS JOIN (VALUES
  ('Artemether/Lumefantrine (AL)'),
  ('Artesunate injection'),
  ('Amoxicillin'),
  ('Amoxicillin/Clavulanic acid'),
  ('Cotrimoxazole'),
  ('Erythromycin'),
  ('Metronidazole'),
  ('Ciprofloxacin'),
  ('Paracetamol'),
  ('Ibuprofen'),
  ('ORS (oral rehydration salts)'),
  ('Zinc sulfate'),
  ('Iron + folic acid'),
  ('Mebendazole'),
  ('Albendazole'),
  ('Promethazine'),
  ('Hydrochlorothiazide'),
  ('Nifedipine'),
  ('Methyldopa'),
  ('Salbutamol inhaler'),
  ('Tetanus toxoid (TT)'),
  ('Vitamin A'),
  ('Magnesium sulfate (severe pre-eclampsia)'),
  ('Oxytocin')
) AS drug(name)
ON CONFLICT (clinic_id, drug_name) DO NOTHING;

-- from 076_billing_itemized.sql:33
INSERT INTO clinic_billing_rates (clinic_id, consultation_fee_ugx)
SELECT id, 5000 FROM clinics
ON CONFLICT (clinic_id) DO NOTHING;

-- from 080_medication_catalog_formulary.sql:146
INSERT INTO clinic_pharmacy_formulary (
  clinic_id, drug_name, medication_code, code, category, in_stock, display_order, active
)
SELECT DISTINCT ON (c.id, LOWER(TRIM(mc.generic_name)))
  c.id,
  mc.generic_name,
  mc.code,
  mc.code,
  mc.category,
  TRUE,
  mc.display_order,
  TRUE
FROM clinics c
CROSS JOIN medication_catalog mc
WHERE mc.active
ORDER BY c.id, LOWER(TRIM(mc.generic_name)), mc.display_order, mc.code
ON CONFLICT (clinic_id, drug_name) DO UPDATE SET
  medication_code = COALESCE(clinic_pharmacy_formulary.medication_code, EXCLUDED.medication_code),
  code = COALESCE(clinic_pharmacy_formulary.code, EXCLUDED.code),
  category = COALESCE(clinic_pharmacy_formulary.category, EXCLUDED.category);

