/**
 * Demo census generator — emits seed/20_demo_census.sql.
 *
 * The cast of the demo clinic: seed staff, 20 fictional patients (longitudinal
 * charts, today's OPD board with one patient per workflow bucket, a month of
 * paid + HMIS-coded history, one active admission), pharmacy stock with FEFO
 * batches. Scenarios are drawn from the KaribuLearn canonical cases
 * (content/learn/generated/hc3-core-draft-v0.1.0); chart-level data is curated
 * against the real catalogs (scripts/demo-seed/catalogs.json).
 *
 * Rules (docs/demo-environment-plan.md §4):
 *   - fixed UUIDs, ON CONFLICT DO NOTHING → idempotent
 *   - ALL dates relative to kampala_today()/NOW() — reseeding is always "today"
 *   - every worklist bucket is targeted via the exact RPC predicates
 *     (rpc_get_opd_patients_today, rpc_worklist_* — see baseline schema)
 *   - zero real PHI: every person is invented
 *
 * Run: pnpm --filter @karibu/supabase-demo generate-census
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..', '..')
const catalogs = JSON.parse(readFileSync(join(HERE, 'catalogs.json'), 'utf8')) as {
  medications: { code: string; name: string; strength: string | null; formulation: string; unit: string; price: number | null }[]
  lab_tests: { code: string; name: string; price: number | null }[]
}

const med = (code: string) => {
  const m = catalogs.medications.find((x) => x.code === code)
  if (!m) throw new Error(`unknown medication code ${code}`)
  return m
}
const lab = (code: string) => {
  const l = catalogs.lab_tests.find((x) => x.code === code)
  if (!l) throw new Error(`unknown lab code ${code}`)
  return l
}

// ── SQL helpers ──────────────────────────────────────────────────────────────
const CLINIC = `'00000000-0000-0000-0000-00000000d310'::uuid`
const uid = (n: number) => `'00000000-0000-4000-8000-${String(n).padStart(12, '0')}'::uuid`
const q = (s: string | null | undefined) => (s == null ? 'NULL' : `'${s.replace(/'/g, "''")}'`)
const day = (n: number) => (n === 0 ? 'kampala_today()' : `(kampala_today() - ${n})`)
const ago = (expr: string) => `(NOW() - INTERVAL '${expr}')`
const CONSULT_FEE = 5000

// Two buffers: stock is emitted into `out` BEFORE the visit buffer (FK order:
// movements/dispense_records reference stock rows), but stock quantities must
// reflect the dispenses the visits create — so visits are generated first
// into `visitOut` while tallying `dispensedByCode`, then stock is emitted with
// on-hand = opening receipts − dispensed, and finally the buffers concatenate.
const out: string[] = []
const visitOut: string[] = []
let sink: string[] = out
const emit = (sql: string) => sink.push(sql)
const dispensedByCode: Record<string, number> = {}

// id namespaces
const S = (n: number) => uid(100 + n) // staff
const P = (n: number) => uid(200 + n) // patients
const V = (n: number) => uid(400 + n) // visits
const VT = (n: number) => uid(700 + n) // vitals
const N = (n: number) => uid(900 + n) // provider notes
const PN = (n: number) => uid(1000 + n) // patient notes
const RX = (n: number) => uid(1100 + n) // prescription orders
const ST = (n: number) => uid(1300 + n) // stock items
const B = (n: number) => uid(1400 + n) // batches
const PAY = (n: number) => uid(1500 + n) // payments
const CH = (n: number) => uid(1600 + n) // charges
const ADM = (n: number) => uid(1800 + n) // admissions
const OBS = (n: number) => uid(1810 + n) // admission observations
const PREG = (n: number) => uid(1850 + n) // pregnancies
const ANC = (n: number) => uid(1860 + n) // anc contacts
const CT = (n: number) => uid(1900 + n) // care tasks
const AP = (n: number) => uid(1950 + n) // appointments
const REF = (n: number) => uid(1980 + n) // referrals
const DSP = (n: number) => uid(2000 + n) // dispense records
const MV = (n: number) => uid(2100 + n) // stock movements
let vtN = 0, nN = 0, pnN = 0, rxN = 0, payN = 0, chN = 0, dspN = 0, mvN = 0, ctN = 0, apN = 0

// ── Header + clinic ──────────────────────────────────────────────────────────
emit(`-- ============================================================================
-- Demo census — GENERATED by scripts/demo-seed/generate-census.ts. Do not edit.
-- Fictional clinic, staff, and patients. All dates relative to kampala_today().
-- ============================================================================

INSERT INTO clinics (id, name, slug, timezone, level, district, receipt_prefix, is_active)
VALUES (${CLINIC}, 'St. Monica HC III (Demo)', 'st-monica-demo', 'Africa/Kampala', 'HC III', 'Kayonza', 'STM', TRUE)
ON CONFLICT (id) DO NOTHING;`)

// ── Staff ────────────────────────────────────────────────────────────────────
const STAFF = [
  { id: S(1), key: 'co', name: 'Dr. Amina Ssebunya', role: 'clinical_officer', email: 'amina.ssebunya@demo.karibu.health' },
  { id: S(2), key: 'nurse', name: 'Agnes Tumushabe', role: 'nurse', email: 'agnes.tumushabe@demo.karibu.health' },
  { id: S(3), key: 'records', name: 'Isaac Kato', role: 'records_officer', email: 'isaac.kato@demo.karibu.health' },
  { id: S(4), key: 'lab', name: 'Peace Muhereza', role: 'lab_tech', email: 'peace.muhereza@demo.karibu.health' },
  { id: S(5), key: 'disp', name: 'Denis Owor', role: 'dispenser', email: 'denis.owor@demo.karibu.health' },
]
const staff = Object.fromEntries(STAFF.map((s) => [s.key, s.id]))
emit(`\n-- Seed staff (authors of historical records; never log in — real users get their own rows via Clerk)`)
for (const s of STAFF) {
  emit(`INSERT INTO staff (id, clerk_user_id, clinic_id, email, display_name, role, is_active, onboarding_completed_at)
VALUES (${s.id}, 'demo_seed_${s.key}', ${CLINIC}, ${q(s.email)}, ${q(s.name)}, '${s.role}', TRUE, NOW())
ON CONFLICT (id) DO NOTHING;`)
}

// ── Patients ─────────────────────────────────────────────────────────────────
type Patient = {
  n: number; first: string; last: string; sex: 'M' | 'F'
  dob?: string; ageYears?: number; ageMonths?: number
  village: string; guardian?: [string, string]
}
const PATIENTS: Patient[] = [
  { n: 1, first: 'Grace', last: 'Asiimwe', sex: 'F', dob: '1968-03-12', village: 'Kibale' },
  { n: 2, first: 'Robert', last: 'Tumusiime', sex: 'M', dob: '1985-07-30', village: 'Rwentobo' },
  { n: 3, first: 'Joy', last: 'Namara', sex: 'F', dob: '2002-01-18', village: 'Kayonza Central' },
  { n: 4, first: 'Wilson', last: 'Baguma', sex: 'M', dob: '1963-11-02', village: 'Nyamirama' },
  { n: 5, first: 'Moses', last: 'Byaruhanga', sex: 'M', ageYears: 29, village: 'Kibale' },
  { n: 6, first: 'Prudence', last: 'Atuhaire', sex: 'F', ageYears: 4, village: 'Kayonza Central', guardian: ['Doreen Atuhaire', 'mother'] },
  { n: 7, first: 'James', last: 'Okello', sex: 'M', ageYears: 52, village: 'Rwentobo' },
  { n: 8, first: 'Beatrice', last: 'Kyomuhendo', sex: 'F', ageYears: 33, village: 'Nyamirama' },
  { n: 9, first: 'Aisha', last: 'Nansubuga', sex: 'F', ageYears: 26, village: 'Kayonza Central' },
  { n: 10, first: 'Elijah', last: 'Ndyamuhaki', sex: 'M', ageMonths: 18, village: 'Kibale', guardian: ['Ruth Ndyamuhaki', 'mother'] },
  { n: 11, first: 'Florence', last: 'Katusiime', sex: 'F', ageYears: 31, village: 'Rwentobo' },
  { n: 12, first: 'Charles', last: 'Mugisha', sex: 'M', ageYears: 36, village: 'Nyamirama' },
  { n: 13, first: 'Patience', last: 'Ainembabazi', sex: 'F', ageYears: 7, village: 'Kibale', guardian: ['Jane Ainembabazi', 'mother'] },
  { n: 14, first: 'Ruth', last: 'Nabukenya', sex: 'F', ageYears: 22, village: 'Kayonza Central' },
  { n: 15, first: 'Dan', last: 'Turyahabwe', sex: 'M', ageYears: 9, village: 'Rwentobo', guardian: ['Samuel Turyahabwe', 'father'] },
  { n: 16, first: 'Allen', last: 'Kembabazi', sex: 'F', ageYears: 29, village: 'Nyamirama' },
  { n: 17, first: 'Kevin', last: 'Amanya', sex: 'M', ageYears: 19, village: 'Kibale' },
  { n: 18, first: 'Sylvia', last: 'Komugisha', sex: 'F', ageYears: 48, village: 'Kayonza Central' },
  { n: 19, first: 'Brian', last: 'Katwesige', sex: 'M', ageYears: 3, village: 'Rwentobo', guardian: ['Harriet Katwesige', 'mother'] },
  { n: 20, first: 'Margaret', last: 'Kansiime', sex: 'F', ageYears: 67, village: 'Nyamirama' },
]
emit(`\n-- Patients (invented; children use age_estimate with guardians)`)
for (const p of PATIENTS) {
  const approxAge = p.ageMonths != null ? Math.floor(p.ageMonths / 12) : p.ageYears
  const cols = p.dob
    ? `date_of_birth, dob_precision`
    : `approximate_age, age_recorded_at, dob_precision`
  const vals = p.dob ? `'${p.dob}', 'exact'` : `${approxAge}, NOW(), 'age_estimate'`
  const guardian = p.guardian ? `, guardian_name, guardian_relationship` : ''
  const gvals = p.guardian ? `, ${q(p.guardian[0])}, '${p.guardian[1]}'` : ''
  emit(`INSERT INTO patients (id, clinic_id, first_name, last_name, sex, ${cols}, village, district${guardian})
VALUES (${P(p.n)}, ${CLINIC}, ${q(p.first)}, ${q(p.last)}, '${p.sex}', ${vals}, ${q(p.village)}, 'Kayonza'${gvals})
ON CONFLICT (id) DO NOTHING;`)
}

// ── Pharmacy stock config ────────────────────────────────────────────────────
// finalQty = quantity remaining ON HAND after the census's dispenses;
// opening receipt = finalQty + total dispensed by seeded visits (computed
// in the second pass, emitStock()). AL final is LOW (demo beat); one AMOX
// batch is near expiry (demo beat).
type Batch = { finalQty: number; expiresDays: number; batchNo: string }
const STOCK: { n: number; code: string; threshold: number; batches: Batch[] }[] = [
  { n: 1, code: 'AL', threshold: 30, batches: [{ finalQty: 12, expiresDays: 240, batchNo: 'AL-2603' }] },
  { n: 2, code: 'AMOX', threshold: 60, batches: [{ finalQty: 60, expiresDays: 20, batchNo: 'AMX-2511' }, { finalQty: 180, expiresDays: 300, batchNo: 'AMX-2606' }] },
  { n: 3, code: 'COTRIM', threshold: 60, batches: [{ finalQty: 400, expiresDays: 400, batchNo: 'CTX-2610' }] },
  { n: 4, code: 'PARA', threshold: 100, batches: [{ finalQty: 500, expiresDays: 500, batchNo: 'PCM-2701' }] },
  { n: 5, code: 'IBU', threshold: 60, batches: [{ finalQty: 300, expiresDays: 420, batchNo: 'IBU-2608' }] },
  { n: 6, code: 'ORS', threshold: 20, batches: [{ finalQty: 80, expiresDays: 350, batchNo: 'ORS-2604' }] },
  { n: 7, code: 'ZINC', threshold: 40, batches: [{ finalQty: 150, expiresDays: 380, batchNo: 'ZN-2605' }] },
  { n: 8, code: 'IRON_FOLATE', threshold: 50, batches: [{ finalQty: 200, expiresDays: 450, batchNo: 'IFA-2609' }] },
  { n: 9, code: 'SALB', threshold: 5, batches: [{ finalQty: 25, expiresDays: 300, batchNo: 'SLB-2603' }] },
  { n: 10, code: 'NIFED', threshold: 30, batches: [{ finalQty: 90, expiresDays: 320, batchNo: 'NIF-2607' }] },
  { n: 11, code: 'HCTZ', threshold: 30, batches: [{ finalQty: 120, expiresDays: 400, batchNo: 'HCT-2606' }] },
  { n: 12, code: 'MGSO4', threshold: 2, batches: [{ finalQty: 6, expiresDays: 500, batchNo: 'MG-2702' }] },
  { n: 13, code: 'CIPRO', threshold: 40, batches: [{ finalQty: 120, expiresDays: 380, batchNo: 'CIP-2605' }] },
  { n: 14, code: 'MEBEND', threshold: 40, batches: [{ finalQty: 100, expiresDays: 410, batchNo: 'MBZ-2608' }] },
  { n: 15, code: 'PRED', threshold: 20, batches: [{ finalQty: 80, expiresDays: 330, batchNo: 'PRD-2604' }] },
]
const stockId: Record<string, string> = Object.fromEntries(STOCK.map((s) => [s.code, ST(s.n)]))
// FEFO batch (earliest-expiring = first listed) per code — dispense movements
// reference it so the apply_pharmacy_stock_movement trigger decrements the
// batch and recomputes the item, exactly as live dispensing does.
const fefoBatch: Record<string, string> = {}
{
  let i = 0
  for (const s of STOCK) {
    fefoBatch[s.code] = B(i + 1)
    i += s.batches.length
  }
}

function emitStock() {
  emit(`\n-- Pharmacy stock. Items and batches start at 0; the census's own 'received'
-- and 'dispensed' movements build the on-hand via apply_pharmacy_stock_movement
-- (the same trigger live dispensing uses), so the ledger reconciles exactly.`)
  let bN = 0
  for (const s of STOCK) {
    const m = med(s.code)
    let remainingDispensed = dispensedByCode[s.code] ?? 0
    emit(`INSERT INTO pharmacy_stock_items (id, clinic_id, drug_code, drug_name, formulation, strength, unit, quantity_on_hand, low_stock_threshold, unit_price_ugx, active)
VALUES (${ST(s.n)}, ${CLINIC}, '${s.code}', ${q(m.name)}, '${m.formulation}', ${q(m.strength)}, '${m.unit}', 0, ${s.threshold}, ${m.price ?? 'NULL'}, TRUE)
ON CONFLICT (id) DO NOTHING;`)
    for (const b of s.batches) {
      bN++
      // FEFO: the earliest-expiring batch absorbs the census dispenses, so its
      // opening receipt = target final qty + everything the visits dispensed.
      const opening = b.finalQty + remainingDispensed
      remainingDispensed = 0
      emit(`INSERT INTO pharmacy_stock_batches (id, stock_item_id, clinic_id, batch_number, expires_at, quantity_on_hand, received_at, active)
VALUES (${B(bN)}, ${ST(s.n)}, ${CLINIC}, '${b.batchNo}', ${day(-b.expiresDays)}, 0, ${ago('160 days')}, TRUE)
ON CONFLICT (id) DO NOTHING;`)
      mvN++
      emit(`INSERT INTO pharmacy_stock_movements (id, stock_item_id, clinic_id, movement_type, quantity_delta, batch_number, batch_id, recorded_by, notes, created_at)
VALUES (${MV(mvN)}, ${ST(s.n)}, ${CLINIC}, 'received', ${opening}, '${b.batchNo}', ${B(bN)}, ${staff.disp}, 'Opening stock', ${ago('160 days')})
ON CONFLICT (id) DO NOTHING;`)
    }
  }
}

// ── Visit machinery ──────────────────────────────────────────────────────────
type LabEntry = { code: string; status: 'pending' | 'running' | 'done'; result?: string; abnormal?: boolean }
type RxLine = { code: string; dose: string; freq: string; days: number; qty: number; dispensed?: boolean }
type VisitSpec = {
  v: number; p: number; daysAgo: number
  cc: string; dept?: string
  queue: string; status: string; priority?: string
  docComplete?: boolean
  vitals?: { w?: number; t?: number; bps?: number; bpd?: number; pulse?: number; rr?: number; spo2?: number; muac?: number }
  note?: { text: string; signed: boolean }
  labs?: LabEntry[]
  rx?: RxLine[]; pharmacySubmitted?: boolean; dispensingStatus?: string
  diagnosis?: string; hmis?: string[]
  paid?: 'cash' | 'mtn_momo' | 'waived' | null
  followUp?: string
  checkedInMinAgo?: number
  admissionId?: string
}

function labJson(entries: LabEntry[], daysAgo: number): { json: string; status: string; results: string | null; abnormal: boolean } {
  const parts = entries.map((e) => {
    const name = lab(e.code).name
    const done = e.status === 'done'
    return `jsonb_build_object('test', ${q(name)}, 'status', ${q(done && e.abnormal ? 'done' : e.status)}, 'result', ${done ? q(e.result ?? null) : 'NULL'}, 'abnormal', ${e.abnormal ? 'TRUE' : 'FALSE'}, 'started_at', ${e.status === 'pending' ? 'NULL' : `to_jsonb(${ago(`${daysAgo} days 2 hours`)})`}, 'completed_at', ${done ? `to_jsonb(${ago(`${daysAgo} days 1 hour`)})` : 'NULL'})`
  })
  const doneCount = entries.filter((e) => e.status === 'done').length
  const anyRunning = entries.some((e) => e.status === 'running')
  const abnormal = entries.some((e) => e.abnormal)
  let status: string
  if (entries.length === 0) status = 'not_ordered'
  else if (doneCount === 0 && !anyRunning) status = 'pending'
  else if (doneCount < entries.length) status = 'running'
  else status = abnormal ? 'abnormal' : 'done'
  const results =
    doneCount > 0
      ? entries.filter((e) => e.status === 'done').sort((a, b) => lab(a.code).name.localeCompare(lab(b.code).name)).map((e) => `${lab(e.code).name}: ${e.result ?? '—'}`).join('; ')
      : null
  return { json: `jsonb_build_array(${parts.join(', ')})`, status, results, abnormal }
}

function emitVisit(s: VisitSpec) {
  const vid = V(s.v)
  const pid = P(s.p)
  const labs = s.labs ?? []
  const L = labJson(labs, s.daysAgo)
  const testsOrdered = labs.length ? labs.map((e) => lab(e.code).name).join(', ') : null
  const medsText = s.rx?.length ? s.rx.map((r) => `${med(r.code).name} ${r.dose} ${r.freq} x ${r.days}d`).join('; ') : null
  const checkedIn = s.daysAgo === 0 ? ago(`${s.checkedInMinAgo ?? 60} minutes`) : ago(`${s.daysAgo} days 3 hours`)
  // Chart consistency: a visit whose lines were dispensed was necessarily
  // submitted to pharmacy and is dispensing_status='dispensed'.
  const anyDispensed = (s.rx ?? []).some((r) => r.dispensed)
  if (anyDispensed) {
    s.dispensingStatus = s.dispensingStatus ?? 'dispensed'
    s.pharmacySubmitted = s.pharmacySubmitted ?? true
  }
  for (const r of s.rx ?? []) {
    if (r.dispensed) dispensedByCode[r.code] = (dispensedByCode[r.code] ?? 0) + r.qty
  }
  emit(`\n-- visit ${s.v}: patient ${s.p}, ${s.daysAgo === 0 ? 'TODAY' : s.daysAgo + 'd ago'} — ${s.cc}`)
  emit(`INSERT INTO visits (id, clinic_id, patient_id, doctor_id, nurse_id, visit_date, checked_in_at, department,
  status, queue_status, priority, review_status, chief_complaint, diagnosis, medications, follow_up_instructions,
  tests_ordered, lab_test_results, lab_status, lab_results, lab_abnormal, lab_completed_at, lab_completed_by,
  documentation_complete, documentation_completed_at, dispensing_status, dispensed_at, dispensed_by,
  pharmacy_order_submitted_at, pharmacy_order_submitted_by, admission_id)
VALUES (${vid}, ${CLINIC}, ${pid}, ${['waiting', 'with_nurse'].includes(s.queue) ? 'NULL' : staff.co}, ${s.queue === 'waiting' ? 'NULL' : staff.nurse}, ${day(s.daysAgo)}, ${checkedIn}, '${s.dept ?? 'opd'}',
  '${s.status}', '${s.queue}', '${s.priority ?? 'normal'}', '${s.docComplete ? 'reviewed' : 'pending'}', ${q(s.cc)}, ${q(s.diagnosis ?? null)}, ${q(medsText)}, ${q(s.followUp ?? null)},
  ${q(testsOrdered)}, ${L.json}, '${L.status}', ${q(L.results)}, ${L.abnormal ? 'TRUE' : 'FALSE'}, ${L.status === 'done' || L.status === 'abnormal' ? ago(`${s.daysAgo} days 1 hour`) : 'NULL'}, ${L.status === 'done' || L.status === 'abnormal' ? staff.lab : 'NULL'},
  ${s.docComplete ? 'TRUE' : 'FALSE'}, ${s.docComplete ? ago(`${s.daysAgo} days 30 minutes`) : 'NULL'}, '${s.dispensingStatus ?? 'not_started'}', ${s.dispensingStatus === 'dispensed' ? ago(`${s.daysAgo} days 45 minutes`) : 'NULL'}, ${s.dispensingStatus === 'dispensed' ? staff.disp : 'NULL'},
  ${s.pharmacySubmitted ? ago(`${s.daysAgo} days 90 minutes`) : 'NULL'}, ${s.pharmacySubmitted ? staff.co : 'NULL'}, ${s.admissionId ?? 'NULL'})
ON CONFLICT (id) DO NOTHING;`)

  if (s.vitals) {
    vtN++
    const vt = s.vitals
    emit(`INSERT INTO patient_vitals (id, patient_id, visit_id, recorded_at, recorded_by, weight_kg, temp_c, bp_systolic, bp_diastolic, pulse_bpm, resp_rate, spo2_pct, muac_cm)
VALUES (${VT(vtN)}, ${pid}, ${vid}, ${s.daysAgo === 0 ? ago(`${Math.max((s.checkedInMinAgo ?? 60) - 10, 5)} minutes`) : ago(`${s.daysAgo} days 2 hours 30 minutes`)}, ${staff.nurse}, ${vt.w ?? 'NULL'}, ${vt.t ?? 'NULL'}, ${vt.bps ?? 'NULL'}, ${vt.bpd ?? 'NULL'}, ${vt.pulse ?? 'NULL'}, ${vt.rr ?? 'NULL'}, ${vt.spo2 ?? 'NULL'}, ${vt.muac ?? 'NULL'})
ON CONFLICT (id) DO NOTHING;`)
  }

  if (s.note) {
    nN++
    emit(`INSERT INTO provider_notes (id, visit_id, patient_id, transcript, note_content, status, source, created_at, updated_at)
VALUES (${N(nN)}, ${vid}, ${pid}, ${q(s.note.text)}, ${q(s.note.text)}, '${s.note.signed ? 'signed' : 'draft'}', 'visit', ${ago(`${s.daysAgo} days 2 hours`)}, ${ago(`${s.daysAgo} days 1 hour`)})
ON CONFLICT (id) DO NOTHING;`)
    if (s.note.signed) {
      pnN++
      emit(`INSERT INTO patient_notes (id, visit_id, content, language, status, source)
VALUES (${PN(pnN)}, ${vid}, ${q(`Visit summary for the patient: ${s.diagnosis ?? s.cc}. ${s.followUp ?? ''}`.trim())}, 'en', 'finalized', 'ai_generated')
ON CONFLICT (visit_id, source) DO NOTHING;`)
    }
  }

  // prescriptions (+ optional dispense with stock decrement)
  const chargeItems: { desc: string; cat: string; amount: number; qty: number; unit: number | null; code: string | null }[] = []
  chargeItems.push({ desc: 'Consultation fee', cat: 'consultation', amount: CONSULT_FEE, qty: 1, unit: CONSULT_FEE, code: null })
  for (const e of labs) {
    if (e.status === 'done') {
      const l = lab(e.code)
      if (l.price) chargeItems.push({ desc: l.name, cat: 'lab', amount: l.price, qty: 1, unit: l.price, code: e.code })
    }
  }
  for (const r of s.rx ?? []) {
    rxN++
    const rxId = RX(rxN)
    const m = med(r.code)
    const status = r.dispensed ? 'dispensed' : 'ordered'
    emit(`INSERT INTO prescription_orders (id, visit_id, clinic_id, patient_id, sort_order, medication_code, dose_text, frequency_text, duration_text, quantity_prescribed, quantity_unit, status, source, ordered_by, ordered_at)
VALUES (${rxId}, ${vid}, ${CLINIC}, ${pid}, ${rxN}, '${r.code}', ${q(r.dose)}, ${q(r.freq)}, ${q(r.days + ' days')}, ${r.qty}, '${m.unit}', '${status}', 'manual', ${staff.co}, ${ago(`${s.daysAgo} days 90 minutes`)})
ON CONFLICT (id) DO NOTHING;`)
    if (r.dispensed) {
      const sid = stockId[r.code]
      let mvRef = 'NULL'
      if (sid) {
        mvN++
        mvRef = MV(mvN)
        emit(`INSERT INTO pharmacy_stock_movements (id, stock_item_id, clinic_id, movement_type, quantity_delta, visit_id, prescription_order_id, batch_id, recorded_by, created_at)
VALUES (${mvRef}, ${sid}, ${CLINIC}, 'dispensed', ${-r.qty}, ${vid}, ${rxId}, ${fefoBatch[r.code]}, ${staff.disp}, ${ago(`${s.daysAgo} days 45 minutes`)})
ON CONFLICT (id) DO NOTHING;`)
      }
      dspN++
      emit(`INSERT INTO dispense_records (id, prescription_order_id, visit_id, clinic_id, dispensed_by, quantity_dispensed, quantity_unit, line_status, stock_item_id, stock_movement_id, dispensed_at)
VALUES (${DSP(dspN)}, ${rxId}, ${vid}, ${CLINIC}, ${staff.disp}, ${r.qty}, '${m.unit}', 'dispensed', ${sid ?? 'NULL'}, ${mvRef}, ${ago(`${s.daysAgo} days 45 minutes`)})
ON CONFLICT (id) DO NOTHING;`)
      if (m.price) chargeItems.push({ desc: `${m.name} x ${r.qty}`, cat: 'pharmacy', amount: m.price * r.qty, qty: r.qty, unit: m.price, code: r.code })
    }
  }

  // charges + payment (only for visits that reached billing: status sent/completed)
  if (s.status === 'sent' || s.status === 'completed') {
    for (const c of chargeItems) {
      chN++
      emit(`INSERT INTO charges (id, clinic_id, patient_id, visit_id, description, category, amount_ugx, quantity, unit_price_ugx, item_code, source, created_by, created_at)
VALUES (${CH(chN)}, ${CLINIC}, ${pid}, ${vid}, ${q(c.desc)}, '${c.cat}', ${c.amount}, ${c.qty}, ${c.unit ?? 'NULL'}, ${q(c.code)}, 'auto', ${staff.co}, ${ago(`${s.daysAgo} days 40 minutes`)})
ON CONFLICT (id) DO NOTHING;`)
    }
    if (s.paid) {
      payN++
      const total = chargeItems.reduce((a, c) => a + c.amount, 0)
      const method = s.paid === 'waived' ? 'cash' : s.paid
      const status = s.paid === 'waived' ? 'waived' : 'paid'
      emit(`INSERT INTO payments (id, visit_id, clinic_id, patient_id, amount_ugx, payment_method, status, service_type, collected_by, created_at)
VALUES (${PAY(payN)}, ${vid}, ${CLINIC}, ${pid}, ${s.paid === 'waived' ? 0 : total}, '${method}', '${status}', 'opd', ${staff.records}, ${ago(`${s.daysAgo} days 20 minutes`)})
ON CONFLICT (id) DO NOTHING;`)
    }
  }

  for (const code of s.hmis ?? []) {
    emit(`INSERT INTO visit_diagnosis_codes (visit_id, hmis_code_id, source, coded_by)
SELECT ${vid}, id, 'manual', ${staff.co} FROM hmis_diagnosis_codes WHERE hmis_code = '${code}'
ON CONFLICT (visit_id, hmis_code_id) DO NOTHING;`)
  }
}

// ── All visit-level content goes into the second buffer (see note at top) ────
sink = visitOut

// ── Longitudinal: Grace Asiimwe, hypertension (5 visits) ─────────────────────
emit(`\n-- ═══ Longitudinal: Grace Asiimwe — hypertension follow-up (Learn: hypertension-followup-poor-control) ═══`)
const graceVisits = [
  { v: 10, daysAgo: 150, bps: 168, bpd: 104, note: 'New diagnosis of hypertension. BP 168/104 confirmed on repeat. Started HCTZ 25mg OD. Counselled on salt reduction and follow-up.' },
  { v: 11, daysAgo: 120, bps: 154, bpd: 98, note: 'Hypertension review. BP improved but above target. Continued HCTZ, added lifestyle counselling. Reports taking medicine most days.' },
  { v: 12, daysAgo: 90, bps: 150, bpd: 96, note: 'Hypertension review. BP 150/96. Added Nifedipine 20mg BD. Discussed adherence; ran out of tablets for one week last month.' },
  { v: 13, daysAgo: 60, bps: 144, bpd: 92, note: 'Hypertension review. BP 144/92 on HCTZ + Nifedipine. Tolerating well, mild ankle swelling. Continue current treatment.' },
  { v: 14, daysAgo: 21, bps: 152, bpd: 98, note: 'Hypertension review. BP up at 152/98; admits missing evening doses. Reinforced adherence, refilled one month. Review in 4 weeks.' },
]
for (const g of graceVisits) {
  emitVisit({
    v: g.v, p: 1, daysAgo: g.daysAgo, cc: 'Hypertension follow-up and refill',
    queue: 'completed', status: 'completed', docComplete: true,
    vitals: { bps: g.bps, bpd: g.bpd, pulse: 84, t: 36.8, w: 71 },
    note: { text: g.note, signed: true },
    rx: [
      { code: 'HCTZ', dose: '25 mg', freq: 'OD', days: 30, qty: 30, dispensed: true },
      ...(g.daysAgo <= 90 ? [{ code: 'NIFED', dose: '20 mg', freq: 'BD', days: 30, qty: 60, dispensed: true }] : []),
    ],
    diagnosis: 'Hypertension, poorly controlled', hmis: ['HMIS_105_13'], paid: 'cash',
    followUp: 'Take medicines daily. Return in 4 weeks or sooner if headache or blurred vision.',
  })
}
apN++
emit(`INSERT INTO appointments (id, clinic_id, patient_id, event_type, title, reason, scheduled_at, status, created_by)
VALUES (${AP(apN)}, ${CLINIC}, ${P(1)}, 'follow_up', 'BP review — Grace Asiimwe', 'Hypertension follow-up', ${day(-7)}::timestamptz + INTERVAL '9 hours', 'scheduled', ${staff.co})
ON CONFLICT (id) DO NOTHING;`)

// ── Longitudinal: Robert Tumusiime, HIV on ART ───────────────────────────────
emit(`\n-- ═══ Longitudinal: Robert Tumusiime — HIV on ART (Learn: hiv-art-continuity, art-side-effects) ═══`)
emitVisit({
  v: 20, p: 2, daysAgo: 84, cc: 'Tested HIV positive at outreach; enrolment visit',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { bps: 122, bpd: 78, pulse: 80, t: 36.9, w: 64 },
  note: { text: 'HIV rapid test positive, confirmed per algorithm. Counselled; enrolled in care and started on TLD same day per test-and-treat. Cotrimoxazole prophylaxis started. Baseline bloods sent.', signed: true },
  labs: [{ code: 'HIV_RDT', status: 'done', result: 'Positive', abnormal: true }],
  rx: [{ code: 'COTRIM', dose: '960 mg', freq: 'OD', days: 30, qty: 30, dispensed: true }],
  diagnosis: 'HIV infection, newly diagnosed — started on ART', hmis: ['HMIS_105_17'], paid: 'waived',
})
emitVisit({
  v: 21, p: 2, daysAgo: 42, cc: 'ART refill; reports vivid dreams on TLD',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { bps: 118, bpd: 76, pulse: 76, t: 36.7, w: 65 },
  note: { text: 'ART refill visit. Adherent. Vivid dreams settling; counselled to take dose in the morning. Viral load sample taken at 6 weeks per programme. Cotrimoxazole continued.', signed: true },
  labs: [{ code: 'VIRAL_LOAD', status: 'done', result: '<50 copies/mL (suppressed)' }],
  rx: [{ code: 'COTRIM', dose: '960 mg', freq: 'OD', days: 60, qty: 60, dispensed: true }],
  diagnosis: 'HIV on ART, virally suppressed', paid: 'waived',
})
emitVisit({
  v: 22, p: 2, daysAgo: 7, cc: 'ART refill, well',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { bps: 120, bpd: 78, pulse: 74, t: 36.6, w: 66 },
  note: { text: 'Routine ART refill. No complaints, weight stable, adherence good. Next viral load due at 6 months. TB screen negative today.', signed: true },
  rx: [{ code: 'COTRIM', dose: '960 mg', freq: 'OD', days: 90, qty: 90, dispensed: true }],
  diagnosis: 'HIV on ART, stable', paid: 'waived',
})

// ── Longitudinal: Joy Namara, ANC series with pre-eclampsia beat ─────────────
emit(`\n-- ═══ Longitudinal: Joy Namara — ANC series (Learn: pmtct-first-anc, lab-urine-protein-anc, anc-hypertension-danger-signs) ═══`)
emit(`INSERT INTO pregnancies (id, clinic_id, patient_id, lmp, edd, gravida, para, hiv_status, syphilis_status, status, created_by)
VALUES (${PREG(1)}, ${CLINIC}, ${P(3)}, ${day(154)}, ${day(-126)}, 2, 1, 'negative', 'negative', 'active', ${staff.nurse})
ON CONFLICT (id) DO NOTHING;`)
const ancContacts = [
  { n: 1, daysAgo: 84, gw: 10, bps: 112, bpd: 72, w: 58.0, protein: 'negative', notes: 'First ANC contact. HIV and syphilis negative. IPTp not yet due. IFAS started, ITN given.' },
  { n: 2, daysAgo: 42, gw: 16, bps: 118, bpd: 76, w: 59.5, protein: 'negative', notes: 'Second contact. IPTp dose 1 given. Fundal height consistent with dates.' },
  { n: 3, daysAgo: 1, gw: 22, bps: 148, bpd: 96, w: 61.2, protein: '1+', notes: 'Headache reported. BP elevated 148/96 with 1+ proteinuria — pre-eclampsia risk. Reviewed by CO; urgent referral discussed.' },
]
for (const c of ancContacts) {
  emit(`INSERT INTO anc_contacts (id, pregnancy_id, clinic_id, patient_id, contact_number, contact_date, gestation_weeks, bp_systolic, bp_diastolic, weight_kg, urine_protein, iptp_given, ifas_given, itn_given, notes, recorded_by)
VALUES (${ANC(c.n)}, ${PREG(1)}, ${CLINIC}, ${P(3)}, ${c.n}, ${ago(`${c.daysAgo} days`)}, ${c.gw}, ${c.bps}, ${c.bpd}, ${c.w}, ${q(c.protein)}, ${c.n === 2 ? 'TRUE' : 'FALSE'}, TRUE, ${c.n === 1 ? 'TRUE' : 'FALSE'}, ${q(c.notes)}, ${staff.nurse})
ON CONFLICT (id) DO NOTHING;`)
}
emitVisit({
  v: 30, p: 3, daysAgo: 1, cc: 'ANC visit: headache, high BP', dept: 'anc', priority: 'high',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { bps: 148, bpd: 96, pulse: 92, t: 36.9, w: 61.2 },
  note: { text: 'ANC contact 3 at 22 weeks. Headache, BP 148/96, urine protein 1+. Pre-eclampsia risk identified. Counselled on danger signs; referred to Kayonza General Hospital for obstetric review. To continue IFAS.', signed: true },
  labs: [{ code: 'URINALYSIS', status: 'done', result: 'Protein 1+, otherwise clear', abnormal: true }],
  diagnosis: 'Pregnancy 22 weeks with pre-eclampsia risk', hmis: ['HMIS_105_29'], paid: 'cash',
  followUp: 'Attend hospital obstetric clinic within 48 hours. Return immediately if severe headache, visual changes, or reduced fetal movement.',
})
emit(`INSERT INTO referrals (id, clinic_id, patient_id, visit_id, from_department, to_facility, urgency, reason, clinical_summary, referred_by, status)
VALUES (${REF(1)}, ${CLINIC}, ${P(3)}, ${V(30)}, 'anc', 'Kayonza General Hospital', 'urgent', 'Pre-eclampsia risk at 22 weeks', 'G2P1 at 22/40. BP 148/96, urine protein 1+, headache. IFAS ongoing. Needs obstetric assessment.', ${staff.co}, 'active')
ON CONFLICT (id) DO NOTHING;`)
ctN++
emit(`INSERT INTO care_tasks (id, clinic_id, patient_id, visit_id, task_type, title, description, assignee_role, created_by, due_at, status)
VALUES (${CT(ctN)}, ${CLINIC}, ${P(3)}, ${V(30)}, 'referral_followup', 'Confirm Joy Namara attended hospital referral', 'Pre-eclampsia risk referral made yesterday — call to confirm she was seen.', 'nurse', ${staff.co}, NOW() + INTERVAL '1 day', 'open')
ON CONFLICT (id) DO NOTHING;`)

// ── Longitudinal: Wilson Baguma, diabetes with abnormal RBS ──────────────────
emit(`\n-- ═══ Longitudinal: Wilson Baguma — diabetes (Learn: diabetes-foot-sore, lab-glucose-high) ═══`)
emitVisit({
  v: 40, p: 4, daysAgo: 45, cc: 'Small sore on right foot, slow to heal',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { bps: 138, bpd: 88, pulse: 88, t: 36.8, w: 82 },
  note: { text: 'Known type 2 diabetes on diet control. Small superficial ulcer right heel, no infection signs. Wound care and offloading advised. RBS 11.4 — counselled; review with fasting sugars.', signed: true },
  labs: [{ code: 'RBS', status: 'done', result: '11.4 mmol/L', abnormal: true }],
  diagnosis: 'Type 2 diabetes with foot ulcer, suboptimal control', hmis: ['HMIS_105_14'], paid: 'cash',
})
emitVisit({
  v: 41, p: 4, daysAgo: 10, cc: 'Diabetes review; thirst and passing urine at night',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { bps: 142, bpd: 90, pulse: 90, t: 36.9, w: 81 },
  note: { text: 'Osmotic symptoms recurring. RBS today 18.2 mmol/L — poorly controlled. Foot ulcer healed. Discussed starting oral hypoglycaemic at district clinic; referral letter prepared. Phone follow-up arranged.', signed: true },
  labs: [{ code: 'RBS', status: 'done', result: '18.2 mmol/L', abnormal: true }],
  diagnosis: 'Type 2 diabetes, poorly controlled', hmis: ['HMIS_105_14'], paid: 'mtn_momo',
})
ctN++
emit(`INSERT INTO care_tasks (id, clinic_id, patient_id, visit_id, task_type, title, description, assignee_role, created_by, due_at, status)
VALUES (${CT(ctN)}, ${CLINIC}, ${P(4)}, ${V(41)}, 'phone_callback', 'Call Wilson Baguma re: sugar review', 'RBS 18.2 last visit. Check he has attended district diabetic clinic and how he is feeling.', 'nurse', ${staff.co}, NOW() + INTERVAL '2 days', 'open')
ON CONFLICT (id) DO NOTHING;`)
apN++
emit(`INSERT INTO appointments (id, clinic_id, patient_id, event_type, title, reason, scheduled_at, status, created_by)
VALUES (${AP(apN)}, ${CLINIC}, ${P(4)}, 'follow_up', 'Diabetes review — Wilson Baguma', 'Repeat RBS and medication review', ${day(-14)}::timestamptz + INTERVAL '10 hours', 'scheduled', ${staff.co})
ON CONFLICT (id) DO NOTHING;`)

// ── TODAY'S OPD BOARD — one patient per bucket ───────────────────────────────
emit(`\n-- ═══ TODAY'S OPD BOARD ═══`)
// waiting (queue_status='waiting')
emitVisit({
  v: 50, p: 5, daysAgo: 0, cc: 'Fever and headache for 2 days', checkedInMinAgo: 25,
  queue: 'waiting', status: 'pending',
})
// needs_vitals (queue_status='with_nurse', NO vitals row)
emitVisit({
  v: 51, p: 6, daysAgo: 0, cc: 'Cough and fast breathing (child, 4y)', checkedInMinAgo: 40, priority: 'high',
  queue: 'with_nurse', status: 'pending',
})
// with_clinician (ready_for_doctor/with_doctor + doc incomplete, draft note)
emitVisit({
  v: 52, p: 7, daysAgo: 0, cc: 'Cough for 3 weeks, night sweats', checkedInMinAgo: 75,
  queue: 'with_doctor', status: 'pending',
  vitals: { t: 37.4, bps: 128, bpd: 82, pulse: 92, rr: 20, w: 61 },
  note: { text: 'Cough 3 weeks, night sweats, weight loss ~3kg. No haemoptysis. Household contact with treated TB two years ago. Plan: sputum for GeneXpert, HIV test offered.', signed: false },
})
// awaiting_labs (lab_status running: MRDT running, HB pending)
emitVisit({
  v: 53, p: 8, daysAgo: 0, cc: 'Fever on and off for 3 days, feels weak', checkedInMinAgo: 110,
  queue: 'with_doctor', status: 'pending',
  vitals: { t: 38.3, bps: 110, bpd: 72, pulse: 104, rr: 20, w: 57 },
  note: { text: 'Febrile 3 days, no danger signs. Pale conjunctivae. Malaria RDT and Hb requested; treat according to results.', signed: false },
  labs: [
    { code: 'MRDT', status: 'running' },
    { code: 'HB', status: 'pending' },
  ],
})
// at_pharmacy (order submitted, note still DRAFT — the locked pivot decision)
emitVisit({
  v: 54, p: 9, daysAgo: 0, cc: 'Wheezing and tight chest since last night', checkedInMinAgo: 95, priority: 'high',
  queue: 'with_doctor', status: 'pending',
  vitals: { t: 36.8, bps: 126, bpd: 78, pulse: 112, rr: 28, spo2: 94 },
  note: { text: 'Known asthmatic, exacerbation after dust exposure. Speaking full sentences, wheeze bilateral. Salbutamol given in clinic with good response. Sending inhaler + short prednisolone course to pharmacy while observing; will complete note after review.', signed: false },
  rx: [
    { code: 'SALB', dose: '2 puffs', freq: 'PRN', days: 30, qty: 1 },
    { code: 'PRED', dose: '30 mg', freq: 'OD', days: 5, qty: 15 },
  ],
  pharmacySubmitted: true, dispensingStatus: 'not_started',
})
// ready to bill (status='sent', doc complete, dispensed, NO payment)
emitVisit({
  v: 55, p: 10, daysAgo: 0, cc: 'Watery diarrhoea for 2 days (child, 18 months)', checkedInMinAgo: 160,
  queue: 'completed', status: 'sent', docComplete: true,
  vitals: { w: 10, t: 37.8, pulse: 126, rr: 30 },
  note: { text: 'Watery diarrhoea 2 days, no blood. Restless, sunken eyes, drinks eagerly, skin pinch slow — some dehydration. Plan B: ORS 750 mL over 4 hours in clinic, reassessed and improving. Zinc 20mg OD 10 days. Caregiver counselled on fluids, feeding, danger signs.', signed: true },
  rx: [
    { code: 'ORS', dose: '75 mL/kg', freq: 'over 4h', days: 1, qty: 4, dispensed: true },
    { code: 'ZINC', dose: '20 mg', freq: 'OD', days: 10, qty: 10, dispensed: true },
  ],
  dispensingStatus: 'dispensed', pharmacySubmitted: true,
  diagnosis: 'Acute watery diarrhoea with some dehydration', hmis: ['HMIS_105_3.1'], paid: null,
  followUp: 'Continue ORS after each loose stool. Return immediately if blood in stool, vomiting everything, or drinking poorly.',
})
// done today (completed + paid)
emitVisit({
  v: 56, p: 11, daysAgo: 0, cc: 'Painful boil on left leg', checkedInMinAgo: 210,
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { t: 37.0, bps: 118, bpd: 76, pulse: 82, w: 60 },
  note: { text: 'Furuncle left shin, fluctuant, incised and drained under clean technique. No cellulitis. Wound dressed; amoxicillin course and analgesia given. Dressing review in 3 days.', signed: true },
  rx: [
    { code: 'AMOX', dose: '500 mg', freq: 'TDS', days: 5, qty: 15, dispensed: true },
    { code: 'PARA', dose: '1 g', freq: 'TDS', days: 3, qty: 9, dispensed: true },
  ],
  dispensingStatus: 'dispensed', pharmacySubmitted: true,
  diagnosis: 'Skin abscess, incised and drained', hmis: ['HMIS_105_6'], paid: 'cash',
})

// ── History (closed, paid, HMIS-coded) ───────────────────────────────────────
emit(`\n-- ═══ Past month of closed visits (reports/HMIS data) ═══`)
emitVisit({
  v: 60, p: 12, daysAgo: 3, cc: 'Fever, chills, body aches',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { t: 38.9, bps: 118, bpd: 74, pulse: 108, w: 68 },
  note: { text: 'Classic malaria picture. MRDT positive. Uncomplicated — no danger signs. AL weight-band dosed, first dose observed. Counselled to complete course.', signed: true },
  labs: [{ code: 'MRDT', status: 'done', result: 'Positive (P. falciparum)', abnormal: true }],
  rx: [{ code: 'AL', dose: '4 tabs', freq: 'BD', days: 3, qty: 24, dispensed: true }],
  diagnosis: 'Malaria, confirmed, uncomplicated', hmis: ['HMIS_105_1.1'], paid: 'cash',
})
emitVisit({
  v: 61, p: 13, daysAgo: 5, cc: 'Right ear pain and fever (child, 7y)',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { t: 38.2, pulse: 110, w: 22 },
  note: { text: 'Acute otitis media right ear — red bulging drum. No mastoid tenderness. Amoxicillin 5 days, paracetamol for pain. Return if swelling behind ear or discharge.', signed: true },
  rx: [
    { code: 'AMOX', dose: '250 mg', freq: 'TDS', days: 5, qty: 15, dispensed: true },
    { code: 'PARA', dose: '250 mg', freq: 'TDS', days: 3, qty: 9, dispensed: true },
  ],
  diagnosis: 'Acute otitis media', hmis: ['HMIS_105_8'], paid: 'cash',
})
emitVisit({
  v: 62, p: 14, daysAgo: 8, cc: 'Burning on urination, frequency',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { t: 37.2, bps: 112, bpd: 70, pulse: 84, w: 55 },
  note: { text: 'Dysuria and frequency 3 days. Not pregnant (UCG negative). Urinalysis: leukocytes ++, nitrites positive. Uncomplicated UTI — ciprofloxacin 3 days, fluids.', signed: true },
  labs: [
    { code: 'URINALYSIS', status: 'done', result: 'Leukocytes ++, nitrites +', abnormal: true },
    { code: 'UCG', status: 'done', result: 'Negative' },
  ],
  rx: [{ code: 'CIPRO', dose: '500 mg', freq: 'BD', days: 3, qty: 6, dispensed: true }],
  diagnosis: 'Urinary tract infection, uncomplicated', hmis: ['HMIS_105_4'], paid: 'mtn_momo',
})
emitVisit({
  v: 63, p: 15, daysAgo: 12, cc: 'Abdominal pain around umbilicus (child, 9y)',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { t: 36.9, pulse: 96, w: 26 },
  note: { text: 'Recurrent periumbilical pain, good appetite, no fever. Stool microscopy: ascaris ova. Mebendazole given; household deworming advised.', signed: true },
  labs: [{ code: 'STOOL_OC', status: 'done', result: 'Ascaris lumbricoides ova seen', abnormal: true }],
  rx: [{ code: 'MEBEND', dose: '100 mg', freq: 'BD', days: 3, qty: 6, dispensed: true }],
  diagnosis: 'Intestinal worms (ascariasis)', hmis: ['HMIS_105_5'], paid: 'cash',
})
emitVisit({
  v: 64, p: 16, daysAgo: 15, cc: 'Tiredness and dizziness, 14 weeks pregnant',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { t: 36.7, bps: 104, bpd: 66, pulse: 96, w: 54 },
  note: { text: 'Fatigue in second trimester. Conjunctival pallor. Hb 8.9 — moderate anaemia. Iron/folate started, deworming deferred to ANC, dietary counselling. Recheck Hb in 4 weeks at ANC.', signed: true },
  labs: [{ code: 'HB', status: 'done', result: '8.9 g/dL', abnormal: true }],
  rx: [{ code: 'IRON_FOLATE', dose: '1 tab', freq: 'OD', days: 30, qty: 30, dispensed: true }],
  diagnosis: 'Anaemia in pregnancy, moderate', hmis: ['HMIS_105_12'], paid: 'cash',
})
emitVisit({
  v: 65, p: 17, daysAgo: 18, cc: 'Leg wound from boda accident',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { t: 36.8, bps: 124, bpd: 78, pulse: 88, w: 63 },
  note: { text: 'Laceration left calf from road traffic accident, no fracture signs. Cleaned and sutured. Tetanus toxoid given. Analgesia; review for suture removal in 7 days.', signed: true },
  rx: [
    { code: 'IBU', dose: '400 mg', freq: 'TDS', days: 3, qty: 9, dispensed: true },
    { code: 'TT', dose: '0.5 mL', freq: 'STAT', days: 1, qty: 1, dispensed: false },
  ],
  diagnosis: 'Road traffic injury — laceration, sutured', hmis: ['HMIS_105_10'], paid: 'cash',
})
emitVisit({
  v: 66, p: 18, daysAgo: 22, cc: 'Fever for a week, abdominal discomfort',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { t: 38.4, bps: 116, bpd: 74, pulse: 96, w: 66 },
  note: { text: 'Stepwise fever one week, MRDT negative, Widal suggestive with compatible clinical picture. Treated as typhoid with ciprofloxacin 7 days. Safe water counselling.', signed: true },
  labs: [
    { code: 'MRDT', status: 'done', result: 'Negative' },
    { code: 'WIDAL', status: 'done', result: 'O 1:320, H 1:160', abnormal: true },
  ],
  rx: [{ code: 'CIPRO', dose: '500 mg', freq: 'BD', days: 7, qty: 14, dispensed: true }],
  diagnosis: 'Typhoid fever (clinical + Widal)', hmis: ['HMIS_105_22'], paid: 'cash',
})
emitVisit({
  v: 67, p: 19, daysAgo: 25, cc: 'Runny nose and cough (child, 3y)',
  queue: 'completed', status: 'completed', docComplete: true,
  vitals: { t: 37.6, pulse: 118, rr: 28, w: 13 },
  note: { text: 'URTI — clear chest, no fast breathing, feeding well. Symptomatic care with paracetamol. Danger sign counselling for caregiver. Fee waived (indigent register).', signed: true },
  rx: [{ code: 'PARA', dose: '125 mg', freq: 'TDS', days: 3, qty: 9, dispensed: true }],
  diagnosis: 'Upper respiratory tract infection', hmis: ['HMIS_105_25'], paid: 'waived',
})

// ── Active admission: Margaret Kansiime ──────────────────────────────────────
emit(`\n-- ═══ Active inpatient: Margaret Kansiime (Learn: severe-dehydration-adult) ═══`)
emit(`INSERT INTO admissions (id, clinic_id, patient_id, admitted_at, ward, ward_label, chief_complaint, status, created_by, provisional_dx)
VALUES (${ADM(1)}, ${CLINIC}, ${P(20)}, ${ago('26 hours')}, 'general', 'Bed 2', 'Profuse watery diarrhoea and weakness', 'active', ${staff.co}, 'Severe dehydration secondary to acute gastroenteritis')
ON CONFLICT (id) DO NOTHING;`)
emitVisit({
  v: 70, p: 20, daysAgo: 1, cc: 'Profuse watery diarrhoea, too weak to stand', priority: 'urgent',
  queue: 'completed', status: 'pending', admissionId: ADM(1),
  vitals: { t: 37.1, bps: 92, bpd: 60, pulse: 118, rr: 24, w: 52 },
  note: { text: 'Elderly woman, watery diarrhoea 2 days, lethargic, sunken eyes, skin pinch very slow — severe dehydration. Admitted for IV rehydration per Plan C. ORS alongside as tolerated. Monitoring 4-hourly.', signed: false },
})
const obs = [
  { n: 1, hoursAgo: 18, t: 37.0, bps: 96, bpd: 62, pulse: 112, rr: 24, note: 'On IV fluids, passing urine' },
  { n: 2, hoursAgo: 10, t: 36.8, bps: 104, bpd: 66, pulse: 98, rr: 22, note: 'Improving; taking ORS well' },
  { n: 3, hoursAgo: 2, t: 36.7, bps: 110, bpd: 70, pulse: 88, rr: 18, note: 'Alert, diarrhoea settling' },
]
for (const o of obs) {
  emit(`INSERT INTO admission_observations (id, admission_id, clinic_id, patient_id, observed_at, temp_c, bp_systolic, bp_diastolic, pulse_bpm, resp_rate, avpu, note, recorded_by)
VALUES (${OBS(o.n)}, ${ADM(1)}, ${CLINIC}, ${P(20)}, ${ago(`${o.hoursAgo} hours`)}, ${o.t}, ${o.bps}, ${o.bpd}, ${o.pulse}, ${o.rr}, 'A', ${q(o.note)}, ${staff.nurse})
ON CONFLICT (id) DO NOTHING;`)
}

// ── Assemble: base + stock (with reconciled quantities), then visits ─────────
sink = out
emitStock()
const sql = [...out, ...visitOut].join('\n') + '\n'
writeFileSync(join(ROOT, 'seed', '20_demo_census.sql'), sql)
console.log(`Wrote seed/20_demo_census.sql (${sql.split('\n').length} lines)`)
console.log(`  staff=${STAFF.length} patients=${PATIENTS.length} visits≈${(sql.match(/INSERT INTO visits /g) || []).length} rx=${rxN} payments=${payN} charges=${chN}`)
