#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

# Builds the COPY-PASTE bundle for the Supabase dashboard SQL editor, for
# provisioning the demo project without any local CLI tooling.
#
#   sql-editor/01_schema_part_*.sql    full prod schema = migrations 001-105
#                                      minus demo seeds 004/012/014, chunked
#                                      into editor-friendly parts
#   sql-editor/05_migration_history.sql  marks the chain applied (optional but
#                                      recommended — enables `supabase db push`
#                                      later without re-running anything)
#   sql-editor/06_seed.sql             buckets + catalogs + demo clinic +
#                                      per-clinic backfill + onboarding unlock
#   sql-editor/99_reset_and_reseed.sql one-paste reset: truncate clinical data,
#                                      clear audio objects, reseed, unlock
#
# Paste into the DEMO project's SQL editor in filename order. Never paste
# 99_reset_and_reseed.sql into production.

MIG="../supabase/migrations"
OUT="sql-editor"
CHUNK_BYTES=240000
rm -rf "$OUT"
mkdir -p "$OUT"

# ── Schema parts ─────────────────────────────────────────────────────────────
# Source: the consolidated END-STATE baseline (migrations/0001_baseline.sql,
# built by scripts/build-baseline-local.sh on a local shadow Postgres). We do
# NOT replay migration history — history contains statements newer Supabase
# projects reject (e.g. direct storage DML) and objects that were later
# dropped. Chunks split only at pg_dump object boundaries ("-- Name:" headers)
# so no statement is ever cut in half.
BASELINE="migrations/0001_baseline.sql"
if [[ ! -f "$BASELINE" ]]; then
  echo "error: $BASELINE not found — run scripts/build-baseline-local.sh first." >&2
  exit 1
fi

awk -v cap=$CHUNK_BYTES -v dir="$OUT" '
BEGIN {
  part = 1
  size = 0
  file = dir "/01_schema_part_" part ".sql"
  print "-- Karibu demo schema END STATE, part " part ". GENERATED by build-sql-editor-bundle.sh." > file
  print "-- Paste parts into the DEMO project SQL editor in order." >> file
}
{
  if (size > cap && $0 ~ /^-- Name: /) {
    part++
    size = 0
    file = dir "/01_schema_part_" part ".sql"
    print "-- Karibu demo schema END STATE, part " part ". GENERATED by build-sql-editor-bundle.sh." > file
    # Every part runs as a fresh session: replicate the pg_dump preamble
    # (check_function_bodies especially — SQL function bodies reference
    # sibling objects unqualified and must not be validated at CREATE time).
    print "SET statement_timeout = 0;" >> file
    print "SET lock_timeout = 0;" >> file
    print "SET client_encoding = '\''UTF8'\'';" >> file
    print "SET standard_conforming_strings = on;" >> file
    print "SELECT pg_catalog.set_config('\''search_path'\'', '\'''\'', false);" >> file
    print "SET check_function_bodies = false;" >> file
    print "SET row_security = off;" >> file
  }
  print >> file
  size += length($0) + 1
}
END { print part }
' "$BASELINE" > /tmp/karibu_bundle_parts.txt
total_parts=$(cat /tmp/karibu_bundle_parts.txt)

# ── Migration history ────────────────────────────────────────────────────────
{
  echo "-- Marks the production migration chain as applied on the demo project."
  echo "-- GENERATED. Optional but recommended: makes a future \`supabase db push\`"
  echo "-- apply only migrations newer than this baseline."
  echo "CREATE SCHEMA IF NOT EXISTS supabase_migrations;"
  echo "CREATE TABLE IF NOT EXISTS supabase_migrations.schema_migrations ("
  echo "  version TEXT PRIMARY KEY, statements TEXT[], name TEXT"
  echo ");"
  echo "INSERT INTO supabase_migrations.schema_migrations (version, name) VALUES"
  first=1
  for f in $(ls "$MIG"/*.sql); do
    base=$(basename "$f" .sql)
    v="${base%%_*}"
    n="$base"
    if (( first )); then first=0; else echo ","; fi
    printf "  ('%s', '%s')" "$v" "$n"
  done
  echo ""
  echo "ON CONFLICT (version) DO NOTHING;"
} > "$OUT/05_migration_history.sql"

# ── Seed bundle ──────────────────────────────────────────────────────────────
UNLOCK_SQL="-- Unlock required onboarding (migration 079) for all demo staff.
UPDATE staff SET onboarding_completed_at = COALESCE(onboarding_completed_at, NOW());"

{
  echo "-- Karibu demo seed bundle. GENERATED by build-sql-editor-bundle.sh."
  echo "-- Paste AFTER all schema parts + migration history."
  for s in seed/00_storage_buckets.sql seed/10_reference_data.sql seed/20_demo_census.sql seed/30_clinic_backfill.sql; do
    echo ""
    echo "-- ═══ $(basename "$s") ═══"
    cat "$s"
  done
  echo ""
  echo "$UNLOCK_SQL"
} > "$OUT/06_seed.sql"

# ── Reset-and-reseed (single paste) ──────────────────────────────────────────
# Keep the table list in sync with RESET_TABLES in scripts/db-run.ts.
{
  cat <<'HEADER'
-- ============================================================================
-- DEMO RESET — truncates all clinical/operational data, clears recorded
-- audio, reseeds the census, and unlocks onboarding. Keeps clinics, staff,
-- catalogs, settings, corpus.
--
-- ██ NEVER PASTE THIS INTO THE PRODUCTION PROJECT. ██
-- Check the project name in the dashboard header before running.
-- ============================================================================

DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'visits','patients','patient_vitals','patient_notes','patient_consents',
    'provider_notes','provider_note_addendums','provider_note_amendments',
    'audio_uploads',
    'prescription_orders','dispense_records',
    'pharmacy_stock_items','pharmacy_stock_movements','pharmacy_stock_batches',
    'lab_stock_items','lab_stock_movements',
    'payments','charges',
    'care_tasks',
    'admissions','admission_observations','admission_notes',
    'medication_orders','medication_administrations',
    'iv_infusions','iv_infusion_checks',
    'deliveries','postnatal_observations',
    'pregnancies','anc_contacts',
    'hts_events','hiv_care_enrollments','viral_load_tests',
    'tb_episodes','tb_preventive_treatment',
    'referrals','appointments','ebola_screenings',
    'visit_critical_alerts','visit_diagnosis_codes',
    'ai_review_suggestions','consult_threads','consult_messages',
    'protocol_activations',
    'sync_operations','audit_logs','chart_access_log',
    'patient_number_sequences','payment_receipt_sequences'
  ] LOOP
    IF to_regclass('public.' || t) IS NOT NULL THEN
      EXECUTE format('TRUNCATE TABLE public.%I CASCADE', t);
    END IF;
  END LOOP;
END $$;
HEADER
  for s in seed/10_reference_data.sql seed/20_demo_census.sql seed/30_clinic_backfill.sql; do
    echo ""
    echo "-- ═══ $(basename "$s") ═══"
    cat "$s"
  done
  echo ""
  echo "$UNLOCK_SQL"
} > "$OUT/99_reset_and_reseed.sql"

echo "Bundle written to $OUT/:"
wc -c "$OUT"/*.sql | awk '{printf "  %-38s %6.0f KB\n", $2, $1/1024}' | sed 's|sql-editor/||'
echo "Schema parts: $total_parts"
