#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

# Regenerates the reference-data seeds by extracting the data blocks from the
# production migration chain (packages/supabase/migrations). No database
# access needed and zero PHI by construction — everything comes from files
# checked into this repo.
#
#   seed/10_reference_data.sql   global catalogs (safe before any clinic exists)
#   seed/30_clinic_backfill.sql  per-clinic materializations (run AFTER the
#                                census seed has created the demo clinic)
#
# Migrations are immutable once applied, so these extractions are stable.
# NEW reference data added by future migrations does NOT need to land here —
# future migrations are applied to prod and demo alike (see README).

MIG="../supabase/migrations"

# Prints the block starting at the first line containing the fixed string $2
# in file $1, through the first subsequent line that ends with ';'.
extract_block() {
  local file="$1" pattern="$2"
  local start end
  start=$(grep -m1 -n -F "$pattern" "$file" | cut -d: -f1)
  if [[ -z "$start" ]]; then
    echo "error: pattern not found in $file: $pattern" >&2
    exit 1
  fi
  end=$(awk -v s="$start" 'NR >= s && /;[[:space:]]*$/ { print NR; exit }' "$file")
  if [[ -z "$end" ]]; then
    echo "error: no terminating ';' found after line $start in $file" >&2
    exit 1
  fi
  echo "-- from $(basename "$file"):${start}"
  sed -n "${start},${end}p" "$file"
  echo ""
}

{
  echo "-- GENERATED by scripts/build-reference-seed.sh — do not edit by hand."
  echo "-- Global reference data extracted from packages/supabase/migrations."
  echo "-- All statements are idempotent (ON CONFLICT / UPDATE)."
  echo ""
  extract_block "$MIG/064_structured_pharmacy.sql"            "INSERT INTO medication_catalog (code, generic_name, strength, formulation, unit, category)"
  extract_block "$MIG/080_medication_catalog_formulary.sql"   "INSERT INTO medication_catalog ("
  extract_block "$MIG/069_lab_test_catalog.sql"               "INSERT INTO lab_test_catalog (code, test_name, category, specimen, display_order) VALUES"
  extract_block "$MIG/088_hiv_tb_program_registry.sql"        "INSERT INTO lab_test_catalog (code, test_name, category, specimen, display_order) VALUES"
  extract_block "$MIG/076_billing_itemized.sql"               "UPDATE lab_test_catalog SET default_price_ugx = CASE code"
  extract_block "$MIG/076_billing_itemized.sql"               "UPDATE medication_catalog SET default_price_ugx = CASE code"
  extract_block "$MIG/013_hmis_reporting.sql"                 "INSERT INTO hmis_diagnosis_codes (hmis_code, category, subcategory, display_name, icd10_codes, sort_order) VALUES"
  extract_block "$MIG/088_hiv_tb_program_registry.sql"        "INSERT INTO hmis_106a_elements (element_code, report, section, display_name, dhis2_hint, sort_order) VALUES"
  extract_block "$MIG/048_ehr_pilot_architecture.sql"         "INSERT INTO clinical_protocol_definitions (slug, title, description, trigger_hint, steps, lab_bundle, isolation_required)"
} > seed/10_reference_data.sql

{
  echo "-- GENERATED by scripts/build-reference-seed.sh — do not edit by hand."
  echo "-- Per-clinic backfills extracted from packages/supabase/migrations."
  echo "-- Run AFTER seed/20_demo_census.sql (needs clinic rows to exist)."
  echo "-- All statements are idempotent and scoped by SELECT ... FROM clinics."
  echo ""
  extract_block "$MIG/033_clinician_authority_ai_review.sql"  "INSERT INTO clinic_lab_capabilities (clinic_id, test_name, is_available)"
  extract_block "$MIG/033_clinician_authority_ai_review.sql"  "INSERT INTO clinic_pharmacy_formulary (clinic_id, drug_name, in_stock)"
  extract_block "$MIG/076_billing_itemized.sql"               "INSERT INTO clinic_billing_rates (clinic_id, consultation_fee_ugx)"
  extract_block "$MIG/080_medication_catalog_formulary.sql"   "INSERT INTO clinic_pharmacy_formulary ("
} > seed/30_clinic_backfill.sql

echo "Wrote seed/10_reference_data.sql ($(wc -l < seed/10_reference_data.sql | tr -d ' ') lines)"
echo "Wrote seed/30_clinic_backfill.sql ($(wc -l < seed/30_clinic_backfill.sql | tr -d ' ') lines)"
